[package]
name    = "ssh_protocol"
version = "0.1.0"
authors = ["Jasper Van Casteren <jvc@si-int.eu>"]
description = "SSH Protocol plugin for SmartAgent"
repository = "https://github.com/ContinuousC/SmartAgent"
license = "Elastic-2.0"
edition = "2021"
publish = false

[dependencies]
async-ssh2-lite = {version = "0.4.7", features = ["tokio"]}
serde = { version = "1.0", features = [ "derive" ] }
tokio = { version = "1.0", features = ["full"]}

futures = "0.3.25"
async-trait = "0.1"
serde_json = "1.0"
thiserror = "1.0"
log = "0.4.14"
trust-dns-resolver = { version = "0.22.0", features = [ "tokio-runtime" ] }
tap = "1.0"

agent_utils = {registry = "si", path = "../../agent_utils", features = ["key-reader"] }
logger = {registry = "si", path = "../../logger", version = "0.1" }
etc_base = {registry = "si", path = "../../etc_base", version = "0.1" }
protocol = {registry = "si", path = "../../protocol", version = "0.1.2" }
value = {registry = "si", path = "../../value", version = "0.1" }
sshparser-lib = { registry="si" , version="0.2.3" }
