[package]
name    = "api_protocol"
version = "0.1.0"
authors = ["Vincent Stuyck <vst@si-int.eu>"]
repository = "https://github.com/ContinuousC/SmartAgent"
license = "Elastic-2.0"
edition = "2021"
publish = false

[dependencies]
thiserror           = "1.0"
reqwest      		= { version = "0.12.4", features = ["json", "cookies", "native-tls"] }
chrono       		= { version = "0.4.11", features = ["serde"] }
serde        		= { version = "1.0", features = ["derive"] }
tokio               = { version = "1.0", features = [ "fs", "io-util", "net", "time" ] }
ldap3               = { version = "0.11", features = ["tls"] }
serde_json   		= "1.0"
serde-xml-rs		= "0.6"
serde_urlencoded    = "0.7"
xml-rs              = "0.8.4"
log                 = "0.4.14"
lazy_static = "1.4.0"
regex = "1.5.5"
async-trait         = "0.1"
futures             = "0.3.21"
minidom 			= "0.15.2"
handlebars 			= "6.1"
csv 				= "1.1"
jsonpath            = "0.1.1"
async-recursion     = "1.0.0"
native-tls          = "0.2.10"
quick-xml = { version = "0.36", features = ["serialize"] }

rule-engine = { registry = "si", version = "0.1.27" }

agent_utils = { path = "../../agent_utils", features = ["key-reader"]}
agent_serde = { path = "../../agent_serde" }
etc = { path = "../../etc" }
etc_base = { path = "../../etc_base" }
protocol = { path = "../../protocol", features = ["reqwest"] }
value = { path = "../../value" }
uritemplate = { path = "../../uritemplate/"}
rest_protocol = { path = "../rest"}
azure_protocol = { path = "../azure"}
logger = { path = "../../logger" }
tap = "1.0.1"
trust-dns-resolver = "0"

uuid = { version = "1.8.0", features = ["serde"] }
libc = "0.2.154"
nom = "7.1.3"
itertools = "0.13.0"

[features]
mirth-full = []
