[package]
name    = "snmp_protocol"
version = "0.1.0"
authors = ["Maarten Deprez <mdp@si-int.eu>"]
repository = "https://github.com/ContinuousC/SmartAgent"
license = "Elastic-2.0"
edition = "2021"
publish = false


[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
tokio = { version = "1.0", features = [ "fs", "io-util" ] }
tdigest = { version = "0.2.2", features = [ "use_serde" ] }
clap = { version = "3.2.17", features = ["derive"] }
futures = "0.3.25"
async-trait = "0.1"
serde_json = "1.0"
thiserror = "1.0"
simplelog = "0.12.0"
log = "0.4.14"

# rpc = { registry = "si", version = "0.1" }

#netsnmp = { path = "../../external/netsnmp/Source/Rust", features = ["tokio"] }

agent_utils = { path = "../../agent_utils", features = ["key-reader"] }
logger = { path = "../../logger" }
agent_serde = { path = "../../agent_serde" }
etc_base = { path = "../../etc_base" }
protocol = { path = "../../protocol" }
# protocol_daemon = { path = "../../protocol_daemon" }
value = { path = "../../value" }
parking_lot = "0.12.1"
trust-dns-resolver = { version = "0" }