[package]
name    = "powershell_protocol"
version = "0.1.0"
authors = ["Vincent Stuyck <vst@si-int.eu>"]
repository = "https://github.com/ContinuousC/SmartAgent"
license = "Elastic-2.0"
edition = "2021"
publish = false

[dependencies]
serde       = { version = "1.0", features = ["derive"] }
thiserror   = "1.0"
tokio       = { version = "1.0", features = [ "fs", "io-util" ] }
log = "0.4.14"


winrm_rs = { registry = "si", version = "2.3.0" }
# winrm_rs = { path = "../../tryout/winrm_rs/Source/Rust/" }

windows-agent-client = { registry = "si", version = "0.2.4" }
# windows-agent-client = { path = "../../external/WindowsAgent/Source/Rust/client/" }
agent_utils = { path = "../../agent_utils", features = ["key-reader"]}
etc = { path = "../../etc" }
etc_base = { path = "../../etc_base" }
protocol = { path = "../../protocol" }
value = { path = "../../value" }
logger = { path = "../../logger" }
trust-dns-resolver = {version = "0"}
itertools = "0.11.0"
chrono = "0.4.31"
async-trait = "0.1.74"
tap = "1.0.1"
csv = "1.3.0"
serde_json = "1.0"
uuid = { version = "1.5.0", features = ["serde", "v4"] }
handlebars 			= "6.1"
lazy_static = "1.5.0"
