[package]
name    = "rest_protocol"
version = "0.1.0"
authors = ["Maarten Deprez <mdp@si-int.eu>", "Vincent Stuyck <vst@si-int.eu>"]
repository = "https://github.com/ContinuousC/SmartAgent"
license = "Elastic-2.0"
edition = "2021"
publish = false


[dependencies]
reqwest      		= { version = "0.12.7", features = ["json", "cookies", "native-tls"] }
thiserror           = "1.0"
log                 = "0.4.14"
serde        		= { version = "1.0", features = ["derive"] }
serde_json   		= "1.0"
nom          		= "7"
jsonschema		= "0.16"
serde_urlencoded 	= "0.7"

uritemplate = { path = "../../uritemplate/"}