# Created by WATO
# encoding: utf-8


checkgroup_parameters.setdefault('if', [])

checkgroup_parameters['if'] = [
  ( {'assumed_speed_in': 300000000, 'assumed_speed_out': 300000000, 'traffic': [('both', ('upper', ('perc', (90.0, 95.0))))], 'unit': 'bit'}, [], ['SPAINT01A', 'SPAINT01B'], [u'ethernet1/5'] ),
  ( {'traffic': [('both', ('upper', ('perc', (90.0, 95.0))))], 'assumed_speed_out': 300000000, 'assumed_speed_in': 300000000, 'unit': 'bit'}, [], ['SPAINT01A', 'SPAINT01B'], [u'ethernet1/6'] ),
  ( {'unit': 'bit'}, [], ['SPAINT01A', 'SPAINT01B'], [u'ethernet1/8$'] ),
  ( {'unit': 'bit'}, [], ALL_HOSTS, ALL_SERVICES ),
] + checkgroup_parameters['if']


active_checks.setdefault('check_http', [])

active_checks['check_http'] = [
  ( {'url': u'/', 'urlhost': u'insitedev.uzbrussel.be', 'https': True}, [], ['vlrdev01x'], {'description': u'https://insitedev.uzbrussel.be'} ),
  ( {'url': u'/', 'port': u'8080', 'urlhost': u'vlrextdev01x.uzbrussel.be'}, [], ['vlrextdev01x'], {'description': u'http://vlrextdev01x.uzbrussel.be:8080/'} ),
  ( {'url': u'/nginx_status', 'urlhost': u'vdracodev01x.uzbrussel.be'}, [], ['vdracodev01x'], {'description': u'http://vdracodev01x.uzbrussel.be/users/stevenvp.xml'} ),
  ( {'url': u'/launchCRS.html', 'https': True, 'urlhost': u'v3mgrouper04x.uzbrussel.be'}, [], ['v3mgrouper04x'], {'description': u'https://v3mgrouper04x.uzbrussel.be/launchCRS.html'} ),
  ( {'url': u'/', 'https': True, 'urlhost': u'asemon.uzbrussel.be'}, [], ['vasemon01x'], {'description': u'https://asemon.uzbrussel.be'} ),
  ( {'url': u'/forcea', 'urlhost': u'dwhtest.uzbrussel.be', 'https': True}, [], ['vdwhfront02x'], {'description': u'https://dwhtest.uzbrussel.be/forcea'} ),
  ( {'url': u'/', 'urlhost': u'epowerhrtest.uzbrussel.be', 'https': True}, [], ['vepwrhrt01x'], {'description': u'https://epowerhrtest.uzbrussel.be'} ),
  ( {'url': u'/', 'urlhost': u'empoweruz.uzbrussel.be', 'https': True}, [], ['vepwrhrp01x'], {'description': u'https://empoweruz.uzbrussel.be'} ),
  ( {'url': u'/', 'https': True, 'port': u'8448', 'urlhost': u'vtestalf03x.uzbrussel.be'}, [], ['vtestalf03x'], {'description': u'https://vtestalf03x.uzbrussel.be:8448/'} ),
  ( {'url': u'/', 'urlhost': u'humanuz-test.uzbrussel.be', 'https': True}, [], ['vtestalf03x'], {'description': u'https://humanuz-test.uzbrussel.be/'} ),
  ( {'url': u'/solr/admin/', 'port': u'8080', 'urlhost': u'vlrdev02x.uzbrussel.be'}, [], ['vlrdev02x'], {'description': u'http://vlrdev02x.uzbrussel.be:8080/solr/admin/'} ),
  ( {'url': u'/ITransport/Login.aspx?ReturnUrl=%2fITransport', 'urlhost': u'vdiractivetest01x.uzbrussel.be'}, [], ['vdiractivetest01x'], {'description': u'http://vdiractivetest01x.uzbrussel.be/ITransport/Login.aspx?ReturnUrl=%2fITransport'} ),
  ( {'url': u'/', 'urlhost': u'iprovatest.uzbrussel.be', 'https': True}, [], ['viprovatest02x'], {'description': u'https://iprovatest.uzbrussel.be'} ),
  ( {'url': u'/', 'https': True, 'urlhost': u'iprova.uzbrussel.be'}, [], ['viprovaappl01x'], {'description': u'https://iprova.uzbrussel.be'} ),
  ( {'url': u'/solr/#/term', 'port': u'8983', 'urlhost': u'vsolrtermdev01x.uzbrussel.be'}, [], ['vsolrtermdev01x'], {'description': u'http://vsolrtermdev01x:8983/solr/#/term'} ),
  ( {'url': u'/common/dashboard', 'https': True, 'port': u'7081', 'urlhost': u'j2eetest.uzbrussel.be'}, [], ['vweblogicdev01x'], {'description': u'https://j2eetest.uzbrussel.be:7081/common/dashboard'} ),
  ( {'url': u'/common/dashboard', 'urlhost': u'j2eetest.uzbrussel.be', 'port': u'7082', 'https': True}, [], ['vweblogicdev01x'], {'description': u'https://j2eetest.uzbrussel.be:7082/common/dashboard'} ),
  ( {'url': u'/common/dashboard', 'https': True, 'port': u'7083', 'urlhost': u'j2eetest.uzbrussel.be'}, [], ['vweblogicdev01x'], {'description': u'https://j2eetest.uzbrussel.be:7083/common/dashboard'} ),
  ( {'url': u'/mybox', 'https': True, 'port': u'8080', 'urlhost': u'medimailacc.uzbrussel.be'}, [], ['vmedimailacc01x'], {'description': u'https://medimailacc.uzbrussel.be:8080/mybox'} ),
  ( {'url': u'/mybox', 'https': True, 'port': u'8080', 'urlhost': u'medimail.uzbrussel.be'}, [], ['vmedimail02x'], {'description': u'https://medimail.uzbrussel.be:8080/mybox'} ),
  ( {'url': u'/webadmin/Index.action', 'urlhost': u'vmirthdev01x.uzbrussel.be', 'port': u'8443', 'https': True}, [], ['vmirthdev01x'], {'description': u'https://vmirthdev01x.uzbrussel.be:8443/webadmin/Index.action'} ),
  ( {'url': u'/webadmin/Index.action', 'https': True, 'port': u'8444', 'urlhost': u'vmirthdev01x.uzbrussel.be'}, [], ['vmirthdev01x'], {'description': u'https://vmirthdev01x.uzbrussel.be:8444/webadmin/Index.action'} ),
  ( {'url': u'/mososweb/', 'urlhost': u'vmosos02x.uzbrussel.be'}, [], ['vmosos02x'], {'description': u'http://vmosos02x.uzbrussel.be/mososweb/'} ),
  ( {'url': u'/oaziswebsvc/service.asmx', 'https': True, 'urlhost': u'voazistweb01x.uzbrussel.be'}, [], ['voazistweb01x'], {'description': u'https://voazistweb01x/oaziswebsvc/service.asmx'} ),
  ( {'url': u'/carenet/cnlogin.htm', 'urlhost': u'voazistweb01x.uzbrussel.be', 'https': True}, [], ['voazistweb01x'], {'description': u'https://voazistweb01x.uzbrussel.be/carenet/cnlogin.htm'} ),
  ( {'url': u'/RDWeb', 'https': True, 'expect': u'401', 'urlhost': u'vrdsbroker08x.uzbrussel.be'}, [], ['vrdsbroker08x'], {'description': u'https://vrdsbroker08x.uzbrussel.be/RDWeb'} ),
  ( {'url': u'/', 'urlhost': u'vredcapdev01x.uzbrussel.be', 'https': True}, [], ['vredcapdev01x'], {'description': u'https://vredcapdev01x.uzbrussel.be/'} ),
  ( {'url': u'/UltimoDevelopment/Ultimo.aspx', 'urlhost': u'ultimodev.uzbrussel.be', 'https': True}, [], ['vultimodev01x'], {'description': u'https://ultimodev.uzbrussel.be/UltimoDevelopment/Ultimo.aspx'} ),
  ( {'url': u'/', 'urlhost': u'topdesktest.uzbrussel.be', 'https': True}, [], ['vtopdeskit02x'], {'description': u'https://topdesktest.uzbrussel.be/'} ),
  ( {'url': u'/admin-console', 'urlhost': u'vfmlgendev01x.uzbrussel.be', 'port': u'16000', 'https': True}, [], ['vfmlgendev01x'], {'description': u'https://vfmlgendev01x.uzbrussel.be:16000/admin-console'} ),
  ( {'url': u'/', 'urlhost': u'saga.uzbrussel.be', 'https': True}, [], ['vsagap01x'], {'description': u'https://saga.uzbrussel.be'} ),
  ( {'url': u'/', 'port': u'8080', 'urlhost': u'vuzbpubweb01x.uzbrussel.be'}, [], ['vuzbpubweb01x'], {'description': u'http://vuzbpubweb01x.uzbrussel.be:8080/'} ),
  ( {'url': u'/forcea', 'urlhost': u'dwh.uzbrussel.be', 'expect': u'401', 'https': True}, [], ['vdwhfront01x'], {'description': u'https://dwh.uzbrussel.be/forcea'} ),
  ( {'url': u'/', 'urlhost': u'brightcnv-nipt-prod.uzbrussel.be', 'https': True}, [], ['vbrighttools01x'], {'description': u'https://brightcnv-nipt-prod.uzbrussel.be'} ),
  ( {'url': u'/', 'urlhost': u'vbrighttools03x.uzbrussel.be', 'https': True}, [], ['vbrighttools03x'], {'description': u'https://vbrighttools03x.uzbrussel.be/'} ),
  ( {'url': u'/web/guest/kamerprijs-meerdaagse-opname', 'https': True, 'urlhost': u'www.uzbrussel.be'}, [], ['vuzbpubweb01x'], {'description': u'https://www.uzbrussel.be'} ),
  ( {'url': u'/web/international', 'https': True, 'urlhost': u'www.uzbrussel.be'}, [], ['vuzbpubweb01x'], {'description': u'https://www.uzbrussel.be'} ),
  ( {'url': u'/', 'urlhost': u'insite.uzbrussel.be'}, [], ['vlrprod01x'], {'description': u'http://insite.uzbrussel.be'} ),
  ( {'url': u'/web/guest/wie-is-wie', 'urlhost': u'insite.uzbrussel.be'}, [], ['vlrprod01x'], {'description': u'http://insite.uzbrussel.be/web/guest/wie-is-wie'} ),
  ( {'url': u'/solr/admin/ping', 'port': u'8080', 'urlhost': u'vlrprod02x.uzbrussel.be'}, [], ['vlrprod02x'], {'description': u'http://vlrprod02x.uzbrussel.be:8080/solr/admin/ping'} ),
  ( {'url': u'/portal', 'urlhost': u'igp.uzbrussel.be', 'https': True}, [], ['vigp01x'], {'description': u'https://igp.uzbrussel.be/portal/'} ),
  ( {'url': u'/', 'urlhost': u'healthdata.uzbrussel.be', 'port': u'8443', 'https': True}, [], ['vhd4dp01x'], {'description': u'https://healthdata.uzbrussel.be:8443/#/login'} ),
  ( {'url': u'/', 'https': True, 'port': u'8448', 'urlhost': u'humanuz.uzbrussel.be'}, [], ['vehr01x'], {'description': u'https://humanuz.uzbrussel.be:8448/'} ),
  ( {'url': u'/nginx_status', 'urlhost': u'vdraco01x.uzbrussel.be'}, [], ['vdraco01x'], {'description': u'http://vdraco01x.uzbrussel.be/users/stevenvp.xml'} ),
  ( {'url': u'/nginx_status', 'urlhost': u'vdraco02x.uzbrussel.be'}, [], ['vdraco02x'], {'description': u'http://vdraco02x.uzbrussel.be/users/stevenvp.xml'} ),
  ( {'url': u'/', 'https': True, 'urlhost': u'mediawiki.uzbrussel.be'}, [], ['vbrighttools02x'], {'description': u'https://mediawiki.uzbrussel.be/'} ),
  ( {'url': u'/forms/frmservlet?config=UZ_PROD', 'urlhost': u'kitry.uzbrussel.be', 'https': True}, [], ['vkitry01x'], {'description': u'https://kitry.uzbrussel.be/forms/frmservlet?config=UZ_PROD'} ),
  ( {'url': u'/RDWeb', 'urlhost': u'vrdsweb1601x.uzbrussel.be', 'expect': u'401', 'https': True}, [], ['vrdsweb1601x'], {'description': u'https://vrdsweb1601x.uzbrussel.be/RDWeb'} ),
  ( {'url': u'/RDWeb', 'https': True, 'expect': u'401', 'urlhost': u'vrdsweb1602x.uzbrussel.be'}, [], ['vrdsweb1602x'], {'description': u'https://vrdsweb1602x.uzbrussel.be/RDWeb'} ),
] + active_checks['check_http']


if only_hosts == None:
    only_hosts = []

only_hosts = [
  ( ['!offline', ], ALL_HOSTS, {'comment': u'Do not monitor hosts with the tag "offline"'} ),
] + only_hosts


active_checks.setdefault('linux_service', [])

active_checks['linux_service'] = [
  ( {'username': u'mnow', 'service': u'tomcat83.service'}, [], ['vweblogicdev01x'], {'description': u'Tomcat 8083'} ),
  ( {'username': u'mnow', 'service': u'asemon_dsp_st_1'}, [], ['vasemon01x'], {'description': u'ASEMON Collector DSP_ST_1'} ),
  ( {'username': u'mnow', 'service': u'asemon_dsp_lab'}, [], ['vasemon01x'], {'description': u'ASEMON Collector DSP_LAB'} ),
  ( {'username': u'mnow', 'service': u'asemon_dsp_sez'}, [], ['vasemon01x'], {'description': u'ASEMON Collector DSP_SEZ'} ),
  ( {'username': u'mnow', 'service': u'httpd'}, [], ['vasemon01x', 'vbrighttools01x', 'vbrighttools03x', 'vbrighttools02x', 'sbrightcore01b'], {'description': u'Apache web server'} ),
  ( {'username': u'mnow', 'service': u'mnow.mount'}, [], ['vkwsmon02x'], {'description': u'Kwsmon Mnow filesystem mount'} ),
  ( {'username': u'mnow', 'service': u'uzbot_redirector.service'}, [], ['vkwsmon02x'], {'description': u'kwsmon uzbot log file redirection van vkwsmon01x'} ),
  ( {'username': u'mnow', 'service': u'filebeat.service'}, [], ['vkwsmon02x'], {'description': u'KWSMon filebeat agent'} ),
  ( {'username': u'mnow', 'service': u'sybase_bulk.mount'}, [], ['vasedev01x'], {'description': u'ASEDEV sybase_bulk.mount'} ),
  ( {'username': u'mnow', 'service': u'syb_data-dst_st_2_c_bulk.mount'}, [], ['vasedev01x'], {'description': u'ASEDEV'} ),
  ( {'username': u'mnow', 'service': u'syb_data-dst_st_2_c.mount'}, [], ['vasedev01x'], {'description': u'ASEDEV syb_data-dst_st_2_c.mount'} ),
  ( {'username': u'mnow', 'service': u'syb_full.mount'}, [], ['vasedev01x'], {'description': u'ASEDEV syb_full.mount'} ),
  ( {'username': u'mnow', 'service': u'syb_log.mount'}, [], ['vasedev01x'], {'description': u'ASEDEV syb_log.mount'} ),
  ( {'username': u'mnow', 'service': u'syb_scratch.mount'}, [], ['vasedev01x'], {'description': u'ASEDEV syb_scratch.mount'} ),
  ( {'username': u'mnow', 'service': u'sybdump_netapp.mount'}, [], ['vasedev01x'], {'description': u'ASEDEV'} ),
  ( {'username': u'mnow', 'service': u'local-sybase-sybsoft.mount'}, [], ['vasedev01x'], {'description': u'ASEDEV local-sybase-sybsoft.mount'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'tomcat6'}, [], ['vlrdev02x', 'vlrprod02x'], {'description': u'tomcat'} ),
  ( {'username': u'mnow', 'service': u'vmtoolsd'}, [], ['vasedev01x', 'vasemon01x', 'vweblogicdev01x', 'vweblogicdev02x', 'vdracodev01x', 'viprovaedit01x'], {'description': u'vmware tools centos'} ),
  ( {'username': u'mnow', 'service': u'open-vm-tools.service'}, [], ['vredcapdev01x'], {'description': u'vmware tools ubuntu'} ),
  ( {'username': u'mnow', 'service': u'apache2.service'}, [], ['vredcapdev01x'], {'description': u'Apache2'} ),
  ( {'username': u'mnow', 'service': u'smb.service'}, [], ['vdracodev01x', 'vdracomgmt01x'], {'description': u'Samba'} ),
  ( {'username': u'mnow', 'service': u'nginx.service'}, [], ['vdracodev01x', 'vdraco01x', 'vdraco02x'], {'description': u'nginx web server'} ),
  ( {'username': u'mnow', 'service': u'weblogic81.service'}, [], ['vweblogicdev01x'], {'description': u'BEA Weblogic 7081'} ),
  ( {'username': u'mnow', 'service': u'tomcat81.service'}, [], ['vweblogicdev01x'], {'description': u'Tomcat 8081'} ),
  ( {'username': u'mnow', 'service': u'j2ee-bea81.mount'}, [], ['vweblogicdev01x'], {'description': u'FS /j2ee/bea81'} ),
  ( {'username': u'mnow', 'service': u'j2ee-tomcat81.mount'}, [], ['vweblogicdev01x'], {'description': u'FS /j2ee/tomcat81'} ),
  ( {'username': u'mnow', 'service': u'weblogic82.service'}, [], ['vweblogicdev01x'], {'description': u'BEA Weblogic 7082'} ),
  ( {'username': u'mnow', 'service': u'j2ee-bea82.mount'}, [], ['vweblogicdev01x'], {'description': u'FS /j2ee/bea82'} ),
  ( {'username': u'mnow', 'service': u'xvfb.service'}, [], ['vweblogicdev01x'], {'description': u'X server'} ),
  ( {'username': u'mnow', 'service': u'weblogic83.service'}, [], ['vweblogicdev01x'], {'description': u'BEA Weblogic 7083'} ),
  ( {'username': u'mnow', 'service': u'j2ee-bea83.mount'}, [], ['vweblogicdev01x'], {'description': u'FS /j2ee/bea83'} ),
  ( {'username': u'mnow', 'service': u'j2ee-tomcat83.mount'}, [], ['vweblogicdev01x'], {'description': u'FS /j2ee/bea83'} ),
  ( {'username': u'mnow', 'service': u'batch-prod.mount'}, [], ['vweblogicdev01x'], {'description': u'FS /batch/prod'} ),
  ( {'username': u'mnow', 'service': u'batch-test.mount'}, [], ['vweblogicdev01x'], {'description': u'FS /batch/test'} ),
  ( {'username': u'mnow', 'service': u'jetty.service'}, [], ['viprovaedit01x'], {'description': u'Jetty Webserver'} ),
  ( {'username': u'mnow', 'service': u'webmin.service'}, [], ['viprovaedit01x'], {'description': u'Linux WebAdmin'} ),
  ( {'username': u'mnow', 'service': u'tomcat82.service'}, [], ['vweblogicdev01x'], {'description': u'Tomcat 7082'} ),
  ( {'username': u'mnow', 'service': u'postgresql.service'}, [], ['vbrighttools01x', 'vbrighttools03x'], {'description': u'PostgreSQL'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'elasticsearch'}, [], ['vuzbpubweb02x'], {'description': u'Elastic Search'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'liferay'}, [], ['vuzbpubweb01x'], {'description': u'Liferay'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'jenkins'}, [], ['vbuild01x'], {'description': u'Jenkins build server'} ),
  ( {'username': u'mnow', 'service': u'jenkins'}, [], ['vbuild02x'], {'description': u'Jenkins build server'} ),
  ( {'username': u'mnow', 'service': u'php-fpm.service'}, [], ['vbrighttools02x'], {'description': u'PHP Service'} ),
  ( {'username': u'mnow', 'service': u'mariadb.service'}, [], ['vbrighttools02x'], {'description': u'MariaDB Service'} ),
  ( {'username': u'mnow', 'service': u'sgeexecd.NGScluster.service'}, [], ['bngs01a', 'bngs02a'], {'description': u'NGS Cluster Service'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'slimsgate-test'}, [], ['vslims02x'], {'description': u'Slims services'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'slimsgate-prod'}, [], ['vslims02x'], {'description': u'Slims services'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'tomcatd-prod'}, [], ['vslims02x'], {'description': u'Slims Tomcat Prod'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'tomcatd-test'}, [], ['vslims02x'], {'description': u'Slims Tomcat Test'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'slimsgatetest'}, [], ['vbdrslims01x'], {'disabled': True, 'description': u'Slimsgatetest-Service'} ),
  ( {'username': u'mnow', 'legacy': True, 'service': u'slimsgate'}, [], ['vbdrslims01x'], {'disabled': True, 'description': u'slimsgate service'} ),
] + active_checks['linux_service']


extra_service_conf.setdefault('max_check_attempts', [])

extra_service_conf['max_check_attempts'] = [
  ( 1, [], ALL_HOSTS, ['Cisco Traps'] ),
  ( 4, [], ['I_hosp62', 'I_hosp63', 'I_hosp43'], [u'Check_MK'] ),
] + extra_service_conf['max_check_attempts']


rule_Cisco_Nexus_Health = [
  ( {'group_defaults': {'changes': {}}, 'grouping_rules': [({'table': {}, 'item': {'entPhysicalName': ('contains', u'PowerSupply-2')}}, {'action': 'exclude'})], 'item_rules': [], 'include_rule': {}, 'group_rules': [], 'item_defaults': {'thresholds': {}}, 'grouping_opts': {}}, [], ['SSRVSW01B'] ),
] + rule_Cisco_Nexus_Health


checkgroup_parameters.setdefault('MS_WIN_Memory_Correlation', [])

checkgroup_parameters['MS_WIN_Memory_Correlation'] = [
  ( {'ram': (98.0, 99.0)}, [], ['vsqltclu01c', 'vsqltclu01d', 'vsqlparch01x', 'vsqlpce01a', 'vsqlpce01b', 'vsqlpce02a', 'vsqlpce02b', 'vsqltcognos01x', 'vsqlcognos01x', 'viprovatest02x', 'vhlatwin01x', 'viprovasql01x'], {'description': u'SQL memory - 98 - 99%'} ),
  ( {'ram': (92.0, 95.0)}, [], ['vtestalf03x', 'vmdidisrv'], {'description': u'RAM : 92 - 95%'} ),
] + checkgroup_parameters['MS_WIN_Memory_Correlation']


snmp_communities = [
  ( 'GyFOAT0nSIIbn1H', ['netw_switch_cisco', ], ALL_HOSTS ),
  ( 'h9Vj57Oj', ['sec_fw_paloalto', ], ALL_HOSTS ),
  ( ('authPriv', 'sha', 'mnownetappv3', 'M0nitorMeNow', 'DES', 'M0nitorMeDES'), ['storage_netapp', ], ALL_HOSTS ),
] + snmp_communities


static_checks.setdefault('MS_WIN_Specific_Process', [])

static_checks['MS_WIN_Specific_Process'] = [
  ( ('MS_WIN_Specific_Process', 'WashersLogger_LT_6049', {'min-count': (1, 1)}), [], ['vsteelco01x'] ),
  ( ('MS_WIN_Specific_Process', 'java', {'min-count': (1, 1)}), [], ['alfrescosrv', 'vmmpgsrv'], {'description': u'Vergaderbeheer'} ),
  ( ('MS_WIN_Specific_Process', 'soffice', {'min-count': (1, 1)}), [], ['vtestalf01x'], {'description': u'Open Office'} ),
  ( ('MS_WIN_Specific_Process', 'AlarmMessengerProcessMonitor', {'min-count': (1, 1)}), [], ['vemergin02x'], {'description': u'Emergin alarm monitor'} ),
  ( ('MS_WIN_Specific_Process', 'java', {'min-count': (1, 1)}), [], ['cr43611'], {'description': u'Monitor Primuz (Java) proces op kiosken'} ),
  ( ('MS_WIN_Specific_Process', 'ILCOMi', {'min-count': (1, 1)}), [], ['vvalab01x'], {'description': u'Valab Ilcomi.exe'} ),
  ( ('MS_WIN_Specific_Process', 'Belzebuth', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM Belzebuth process'} ),
  ( ('MS_WIN_Specific_Process', 'Ganesh', {'min-count': (3, 3)}), [], ['slpm01b'], {'description': u'LPM Ganesh process'} ),
  ( ('MS_WIN_Specific_Process', 'Cerbere', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM Cerbere process'} ),
  ( ('MS_WIN_Specific_Process', 'CommDriverManager', {'min-count': (5, 5)}), [], ['slpm01b'], {'description': u'LPM CommDriverManager process'} ),
  ( ('MS_WIN_Specific_Process', 'DataGuardMonitor', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM DataGuardMonitor process'} ),
  ( ('MS_WIN_Specific_Process', 'Gabriel', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM Gabriel process'} ),
  ( ('MS_WIN_Specific_Process', 'Gaia', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM Gaia process'} ),
  ( ('MS_WIN_Specific_Process', 'LCHM', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM LCHM Export Files process'} ),
  ( ('MS_WIN_Specific_Process', 'LHEM2', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM LHEM2 Export Files process'} ),
  ( ('MS_WIN_Specific_Process', 'LMIK', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM LMIK Export Files process'} ),
  ( ('MS_WIN_Specific_Process', 'Narcisse', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM Narcisse process'} ),
  ( ('MS_WIN_Specific_Process', 'Penelope', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM Penelope process'} ),
  ( ('MS_WIN_Specific_Process', 'Phaeton', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM Phaeton process'} ),
  ( ('MS_WIN_Specific_Process', 'Radio32', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM Radio32 process'} ),
  ( ('MS_WIN_Specific_Process', 'Sechat', {'min-count': (1, 1)}), [], ['slpm01b'], {'description': u'LPM Sechat process'} ),
  ( ('MS_WIN_Specific_Process', 'pilote', {'min-count': (1, 1)}), [], ['vsirscan01x'], {'description': u'Sirscan pilote process'} ),
  ( ('MS_WIN_Specific_Process', 'java', {'min-count': (2, 2)}), [], ['vkwsmon01x'], {'description': u'uzbot java'} ),
  ( ('MS_WIN_Specific_Process', 'TCHistory', {'min-count': (1, 1)}), [], ['vhxlm01x', 'vblueidlm01x'], {'description': u'TCHistory process'} ),
  ( ('MS_WIN_Specific_Process', 'TCLANManager', {'min-count': (1, 1)}), [], ['vhxlm01x', 'vblueidlm01x'], {'description': u'TCLANManager process'} ),
  ( ('MS_WIN_Specific_Process', 'TCServeCenter', {'min-count': (1, 1)}), [], ['vhxsc01x'], {'description': u'TCServeCenter process'} ),
  ( ('MS_WIN_Specific_Process', 'java', {'min-count': (3, 3)}), [], ['v3mgrouper02x'], {'description': u'3M java process'} ),
  ( ('MS_WIN_Specific_Process', 'CGSXpresHost', {'min-count': (2, 2)}), [], ['v3mgrouper02x'], {'description': u'3M CGSXpresHost process'} ),
  ( ('MS_WIN_Specific_Process', 'TCHistoryProxy', {'min-count': (1, 1)}), [], ['vblueidlm01x'], {'description': u'TCHistoryProxy process'} ),
  ( ('MS_WIN_Specific_Process', 'TCServeCenter', {'min-count': (1, 1)}), [], ['vblueidsc01x'], {'description': u'TCServeCenter process'} ),
  ( ('MS_WIN_Specific_Process', 'EPA_CLASSIFIER', {'min-count': (4, 4)}), [], ['vbiognost01x'], {'description': u'Biognost EPA_CLASSIFIER process'} ),
  ( ('MS_WIN_Specific_Process', 'EUROLabOfficeBackup', {'min-count': (1, 1)}), [], ['vbiognost01x'], {'description': u'Biognost EUROLabOfficeBackup process'} ),
  ( ('MS_WIN_Specific_Process', 'EUROLabOfficeAppGuardian', {'min-count': (2, 2)}), [], ['vbiognost01x'], {'description': u'Biognost EUROLabOfficeAppGuardian process'} ),
  ( ('MS_WIN_Specific_Process', 'httpd', {'min-count': (2, 2)}), [], ['vkitry01x'], {'description': u'httpd.exe apache process kitry'} ),
  ( ('MS_WIN_Specific_Process', 'java', {'min-count': (7, 7)}), [], ['vkitry01x'], {'description': u'java process kitry'} ),
  ( ('MS_WIN_Specific_Process', 'WinGuard', {'min-count': (1, 1)}), [], ['vwinguard01x'], {'description': u'WinGuard Process'} ),
] + static_checks['MS_WIN_Specific_Process']


ignored_services = [
  ( [], ALL_HOSTS, ['MSSQLServerADHelper100 Service'] ),
] + ignored_services


ignored_checks = [
  ( ['Cisco_CPU_0_99', 'Cisco_Health_0_99', 'Cisco_Memory_Pool_0_99', 'Cisco_Reload_0_99', 'Cisco_Stack_0_99'], [], ALL_HOSTS ),
] + ignored_checks


host_groups = [
  ( 'Kiosken_inschrijving', [], ['cr43611'], {'description': u'Toevoegen aan groep kiosken_inschrijving'} ),
] + host_groups


checkgroup_parameters.setdefault('MS_WIN_Disk_IO', [])

checkgroup_parameters['MS_WIN_Disk_IO'] = [
  ( {'percent_idle': (0.0, 0.0), 'sec_read': (200, 300), 'sec_write': (200, 300)}, [], ALL_HOSTS ),
] + checkgroup_parameters['MS_WIN_Disk_IO']


snmp_timing = [
  ( {'retries': 2, 'timeout': 20.0}, [], ['I_hosp62', 'I_hosp63', 'I_hosp43', 'I_azkc', 'I_directie2', 'I_fertiliteit', 'I_hemo', 'I_hosp2', 'I_hosp3b', 'I_hosp34', 'I_hosp42', 'I_urgentieb', 'I_hosp52', 'I_hosp53', 'I_urgentiec', 'I_urgentied'] ),
] + snmp_timing


bulkwalk_hosts = [
  ( ['netw_switch_cisco', ], ALL_HOSTS ),
  ( ['sec_fw_paloalto', ], ALL_HOSTS ),
] + bulkwalk_hosts


extra_service_conf.setdefault('check_interval', [])

extra_service_conf['check_interval'] = [
  ( 15.0, [], ALL_HOSTS, ALL_SERVICES ),
] + extra_service_conf['check_interval']


checkgroup_parameters.setdefault('MS_WIN_CPU_Correlation', [])

checkgroup_parameters['MS_WIN_CPU_Correlation'] = [
  ( {'cpu_sustained': (95, 98)}, [], ALL_HOSTS ),
] + checkgroup_parameters['MS_WIN_CPU_Correlation']


static_checks.setdefault('MS_WIN_Services_Specific', [])

static_checks['MS_WIN_Services_Specific'] = [
  ( ('MS_WIN_Services_Specific', 'Confluence200515104513', {}), [], ['vconfluence01x'] ),
  ( ('MS_WIN_Services_Specific', 'Tomcat', {}), [], ['vdwhfront02x', 'vdwhfront01x', 'vtestalf03x', 'vrochevcon01x', 'vascosrv', 'vigp01x', 'vget01x', 'vehr01x'], {'description': u'Tomcat Server'} ),
  ( ('MS_WIN_Services_Specific', 'MSiSCSI', {}), [], ['vdwhfront01x', 'viknow02x', 'bexchmail01a', 'bexchmail01b', 'vcvmain01x', 'vcvmain02x', 'imgvaultuzb', 'imdsqlsrv', 'scvmedia01b', 'vois01x', 'vsccm01x', 'vsccm02x', 'vsccmsql02x', 'vsmartnxt01x', 'vheyex01x', 'vaudit01x', 'vauradb01x', 'variadb01x', 'vcvmedia01x', 'vwinguard01x'], {'description': u'MS iSCSI Service'} ),
  ( ('MS_WIN_Services_Specific', 'W3SVC', {}), [], ['vdwhfront01x', 'vdwhfront02x', 'vepwrhrt01x', 'vdiractivetest01x', 'viprovatest02x', 'vmosos02x', 'voazistappl01x', 'voazistweb01x', 'vothello03x', 'vrdsbroker08x', 'vsaga02x', 'vultimodev01x', 'bexchmail01a', 'bexchmail01b', 'vemergin02x', 'vsagat01x', 'vbesco01x', 'vsagap01x', 'vcvmain01x', 'vcvmain02x', 'vultimoprod01x', 'glucosrv2', 'infinitygwsrv', 'pedigreesrv', 'uzlicsrv', 'vica01x', 'vaqure01x', 'vaseba01x', 'vivsoft01x', 'vlsm01x', 'vois01x', 'vsccm01x', 'vsccm02x', 'vsnap01x', 'vsirscan01x', 'vshavlik01x', 'vprint01x', 'vmosos01x', 'vhxlm01x', 'vhd4dp01x', 'vget01x', 'vevault02x', 'vdiractweb01x', 'vbartender01x', 'variadb01x', 'variaweb01x', 'vfacosrds01x', 'vhoneywrds01x', 'vhoneywebi01x', 'vphonexone01x', 'vhighlander02x', 'vcitm01x', 'vepwrhrp01x', 'viprovaappl01x', 'vitstat01x', 'vrdsweb1601x', 'vrdsweb1602x', 'vothello01x', 'voazispappl01x', 'voazispweb01x'], {'description': u'World Wide Web Service'} ),
  ( ('MS_WIN_Services_Specific', 'IBM_Cognos$', {}), [], ['vdwhfront01x', 'vdwhfront02x', 'vsqltcognos01x'] ),
  ( ('MS_WIN_Services_Specific', 'MEDATECWMGR', {}), [], ['vslaaplabo01x'] ),
  ( ('MS_WIN_Services_Specific', 'HL7', {}), [], ['vslaaplabo01x', 'infinitygwsrv'], {'description': u'HL7 Connector'} ),
  ( ('MS_WIN_Services_Specific', 'BegrotingsApp', {}), [], ['Vbegroting01x'] ),
  ( ('MS_WIN_Services_Specific', 'FileMaker', {}), [], ['fmcrgsrv', 'vfmcrg01x', 'vfmlhem01x', 'vfmlgendev01x', 'vfmpsy01x', 'vfmuzb01x', 'vfmlgen01x', 'inf54'], {'description': u'Filemaker Server'} ),
  ( ('MS_WIN_Services_Specific', 'fmlistner', {}), [], ['vfmuzb01x'], {'description': u'Filemaker Server Listener'} ),
  ( ('MS_WIN_Services_Specific', 'Automate', {}), ['app_skybot', ], ['vskybot01x'], {'comment': u'Automate Schedule Server\n', 'description': u'Automate Schedule Server'} ),
  ( ('MS_WIN_Services_Specific', 'Automate_Schedule_Agent_Server', {}), ['app_skybot', ], ['vsky201201x', 'vsky201601x'], {'description': u'Automate Schedule Agent Server'} ),
  ( ('MS_WIN_Services_Specific', 'ClusSvc', {}), [], ['vsqlpce01a', 'vsqlpce01b', 'vsqlpce02a', 'vsqlpce02b', 'vsqltclu01c', 'vsqltclu01d', 'bexchmail01a', 'bexchmail01b'], {'description': u'Cluster Service'} ),
  ( ('MS_WIN_Services_Specific', 'MSSQLFDLauncher', {}), [], ['vsqlpce01a', 'vsqlpce01b', 'vsqlpce02a', 'vsqlpce02b', 'vsqltclu01c', 'vsqltclu01d', 'viprovatest02x', 'vhoneywebi01x', 'viprovasql01x'], {'description': u'SQL Full-text Filter Daemon Launcher'} ),
  ( ('MS_WIN_Services_Specific', 'MSSQLSERVER', {}), [], ['vsqlpce01a', 'vsqlpce01b', 'vsqlpce02a', 'vsqlpce02b', 'vsqltclu01c', 'vsqltclu01d', 'vdiractivetest01x', 'viprovatest02x', 'vemergin02x', 'imdsqlsrv', 'infinitygwsrv', 'medocsqlsrv', 'pacsweb012456', 'vpauserid01x', 'vaqure01x', 'vnicview01x', 'vnicview02x', 'vhif01x', 'vsccm01x', 'vsccmsql02x', 'vcentervdi01x', 'vsqlrep01x', 'vsqlrep03x', 'vdiractweb01x', 'vauradb01x', 'variadb01x', 'vhoneywebi01x', 'vmusedb01x', 'viprovasql01x', 'vnicview01x', 'vnicview02x'], {'description': u'SQL Server'} ),
  ( ('MS_WIN_Services_Specific', 'SQLSERVERAGENT', {}), [], ['vsqlpce01a', 'vsqlpce01b', 'vsqlpce02a', 'vsqlpce02b', 'vsqltclu01c', 'vsqltclu01d', 'vdiractivetest01x', 'viprovatest02x', 'imdsqlsrv', 'medocsqlsrv', 'pacsweb012456', 'vsccm01x', 'vsccmsql02x', 'vcentervdi01x', 'vsqlrep01x', 'vsqlrep03x', 'vdiractweb01x', 'vauradb01x', 'variadb01x', 'vhoneywebi01x', 'vmusedb01x', 'viprovasql01x'], {'description': u'SQL Server Agent'} ),
  ( ('MS_WIN_Services_Specific', 'MySQL', {}), [], ['alfrescosrv', 'vtestalf01x', 'alfrescoprodsrv', 'vcytosure01x', 'vmysql01x', 'vsozo01x'], {'description': u'MySQL'} ),
  ( ('MS_WIN_Services_Specific', 'WebCTRL_Service', {}), [], ['vwebctrl01x'], {'description': u'WebCTRL Service'} ),
  ( ('MS_WIN_Services_Specific', 'PanTaService', {}), [], ['brdshost1601a', 'brdshost1601b', 'brdshost1602a', 'brdshost1602b', 'brdshost1603a', 'brdshost1603b', 'vrdsp8srv01x', 'vrdsp8srv02x', 'brdsdesktop01a', 'brdsdesktop01b', 'brdsdesktop02a', 'brdsdesktop03a', 'brdsdesktop03b', 'brdsdesktop04a', 'brdsdesktop04b', 'tsso1srv12', 'tsso1srv13', 'homeworksrv01', 'vhomework01x', 'vhomework02x', 'vhomework03x', 'vhomework04x', 'vhomework05x', 'vhomework06x', 'vhomework07x', 'srdsdesktop01a', 'srdsdesktop01b', 'vhighlander01x', 'vfacosrds01x', 'vhighlander02x'], {'comment': u'Palo Alto PAN\n', 'description': u'PanTaService'} ),
  ( ('MS_WIN_Services_Specific', 'SSOManHost', {}), [], ['brdshost1601a', 'brdshost1601b', 'brdshost1602a', 'brdshost1602b', 'brdshost1603a', 'brdshost1603b', 'vrdsp8srv01x', 'vrdsp8srv02x', 'brdsdesktop01a', 'brdsdesktop01b', 'brdsdesktop02b', 'brdsdesktop03a', 'brdsdesktop03b', 'brdsdesktop04a', 'brdsdesktop04b', 'tsso1srv12', 'tsso1srv13', 'srdsdesktop01a', 'srdsdesktop01b'], {'comment': u'Imprivata SSO\n', 'description': u'Imprivata Services'} ),
  ( ('MS_WIN_Services_Specific', 'SessionEnv', {}), [], ['brdshost1601a', 'brdshost1601b', 'brdshost1602a', 'brdshost1602b', 'brdshost1603a', 'brdshost1603b', 'vrdsp8srv01x', 'vrdsp8srv02x', 'brdsdesktop01a', 'brdsdesktop01b', 'brdsdesktop02b', 'brdsdesktop03a', 'brdsdesktop03b', 'brdsdesktop04a', 'brdsdesktop04b', 'tsso1srv12', 'tsso1srv13', 'homeworksrv01', 'vhomework01x', 'vhomework02x', 'vhomework03x', 'vhomework04x', 'vhomework05x', 'vhomework06x', 'vhomework07x', 'srdsdesktop01a', 'srdsdesktop01b', 'vlegacy01x', 'vlegacy02x', 'vinkendaal01x', 'vcytosure01x', 'vhighlander01x', 'vget01x', 'vfacosrds01x', 'vlabords01x', 'vlgenrds01x', 'vhighlander02x', 'vhoneywrds01x', 'vhighlander02x', 'voazisrds01x'], {'description': u'Remote Desktop Configuration'} ),
  ( ('MS_WIN_Services_Specific', 'TermService', {}), [], ['brdshost1601a', 'brdshost1601b', 'brdshost1602a', 'brdshost1602b', 'brdshost1603a', 'brdshost1603b', 'brdshost1604a', 'brdshost1604b', 'brdsdesktop01a', 'brdsdesktop01b', 'brdsdesktop02b', 'brdsdesktop03a', 'brdsdesktop03b', 'brdsdesktop04a', 'brdsdesktop04b', 'tsso1srv12', 'tsso1srv13', 'homeworksrv01', 'vhomework01x', 'vhomework02x', 'vhomework03x', 'vhomework04x', 'vhomework05x', 'vhomework06x', 'vhomework07x', 'srdsdesktop01a', 'srdsdesktop01b', 'vlegacy01x', 'vlegacy02x', 'vinkendaal01x', 'vcytosure01x', 'vhighlander01x', 'vget01x', 'vfacosrds01x', 'vlabords01x', 'vlgenrds01x', 'vfacosrds01x', 'vhighlander02x', 'vhoneywrds01x', 'vhighlander02x', 'voazisrds01x'], {'description': u'TermService'} ),
  ( ('MS_WIN_Services_Specific', 'Sophos', {}), [], ['brdshost1601a', 'brdshost1601b', 'brdshost1602a', 'brdshost1602b', 'brdshost1603a', 'brdshost1603b', 'brdsdesktop01a', 'brdsdesktop01b', 'brdsdesktop02b', 'brdsdesktop03a', 'brdsdesktop03b', 'brdsdesktop04a', 'brdsdesktop04b', 'tsso1srv12', 'tsso1srv13', 'homeworksrv01', 'vhomework01x', 'vhomework02x', 'vhomework03x', 'vhomework04x', 'vhomework05x', 'vhomework06x', 'vhomework07x', 'vrochevcon01x', 'vwhiimport01x', 'vsagat01x', 'srdsdesktop01a', 'srdsdesktop01b', 'vsagap01x', 'vinkendaal01x', 'vcytosue01x', 'vhighlander01x', 'vnicview01x', 'vnicview02x', 'vsophos01x'], {'description': u'Sophos Agent'} ),
  ( ('MS_WIN_Services_Specific', 'SAV', {}), [], ['brdshost1601a', 'brdshost1601b', 'brdshost1602a', 'brdshost1602b', 'brdshost1603a', 'brdshost1603b', 'brdsdesktop01a', 'brdsdesktop01b', 'brdsdesktop02b', 'brdsdesktop03a', 'brdsdesktop03b', 'brdsdesktop04a', 'brdsdesktop04b', 'tsso1srv12', 'tsso1srv13', 'homeworksrv01', 'vhomework01x', 'vhomework02x', 'vhomework03x', 'vhomework04x', 'vhomework05x', 'vhomework06x', 'vhomework07x', 'vrochevcon01x', 'vwhiimport01x', 'vsagat01x', 'srdsdesktop01a', 'srdsdesktop01b', 'vsagap01x', 'vscancdot01x', 'vscancdot02x', 'vscancdot03x', 'vscancdot04x', 'vinkendaal01x', 'vcytosure01x', 'vhighlander01x', 'vnicview01x', 'vnicview02x', 'vsophos01x'], {'description': u'Sophos Anti-Virus'} ),
  ( ('MS_WIN_Services_Specific', 'swi_service', {}), [], ['brdshost1601a', 'brdshost1601b', 'brdshost1602a', 'brdshost1602b', 'brdshost1603a', 'brdshost1603b', 'brdsdesktop01a', 'brdsdesktop01b', 'brdsdesktop02b', 'brdsdesktop03a', 'brdsdesktop03b', 'brdsdesktop04a', 'brdsdesktop04b', 'tsso1srv12', 'tsso1srv13', 'homeworksrv01', 'vhomework01x', 'vhomework02x', 'vhomework03x', 'vhomework04x', 'vhomework05x', 'vhomework06x', 'vhomework07x', 'vrochevcon01x', 'vwhiimport01x', 'vsagat01x', 'srdsdesktop01a', 'srdsdesktop01b', 'vsagap01x', 'vinkendaal01x', 'vcytosure01x', 'vhighlander01x', 'vnicview01x', 'vnicview02x', 'vsophos01x'], {'description': u'Sophos Web Intelligence Service'} ),
  ( ('MS_WIN_Services_Specific', 'DMSOCKSRV', {}), [], ['vsqltcognos01x', 'bsqlpcognos01a'], {'description': u'IBM Cognos Data Manager Socket Server'} ),
  ( ('MS_WIN_Services_Specific', 'ws_sched', {}), [], ['bsqlpcognos01a'], {'description': u'WhereScape Cognos'} ),
  ( ('MS_WIN_Services_Specific', 'HumanUZ_Vaadin', {}), [], ['vtestalf03x', 'vehr01x'], {'description': u'Humanuz eHR'} ),
  ( ('MS_WIN_Services_Specific', 'Cache_c-_intersystems_cache', {}), [], ['viknow02x'], {'description': u'Cach\xe9 DB iKnow'} ),
  ( ('MS_WIN_Services_Specific', 'CACHEhttpd', {}), [], ['viknow02x'], {'description': u'Webserver voor CACHE'} ),
  ( ('MS_WIN_Services_Specific', 'ReportServer', {}), [], ['vdiractivetest01x', 'vaqure01x', 'vsccm01x', 'vsccmsql02x', 'vsqlrep01x', 'vsqlrep03x', 'vlicsrv01x', 'vdiractweb01x', 'vhoneywebi01x'], {'description': u'SQL Server Reporting Services'} ),
  ( ('MS_WIN_Services_Specific', 'alf_tomcat_monitor_service', {}), [], ['valfmedt01x'], {'description': u'Alfresco Tomcat Monitor'} ),
  ( ('MS_WIN_Services_Specific', 'iProva', {}), [], ['viprovatest02x', 'viprovaappl01x'], {'description': u'iProva Services'} ),
  ( ('MS_WIN_Services_Specific', 'NetTcpPortSharing', {}), [], ['viprovatest02x', 'voazistweb01x', 'imgvaultuzb', 'vhif01x', 'vpads01x', 'viprovaappl01x', 'voazispappl01x', 'voazispweb01x'], {'description': u'Net.Tcp Port Sharing Service'} ),
  ( ('MS_WIN_Services_Specific', 'PDFService_Support', {}), [], ['viprovatest02x', 'viprovaappl01x'], {'description': u'Iprova PDFService_Support'} ),
  ( ('MS_WIN_Services_Specific', 'SolrFullTextSearch', {}), [], ['vsolrtermdev01x', 'vsolrterm01x'], {'description': u'SolrFullTextSearch'} ),
  ( ('MS_WIN_Services_Specific', 'Spooler', {}), [], ['vword2pdf02x', 'vprint01x', 'vprint02x', 'vdavinci01x', 'vword2pdf01x'], {'description': u'Print Spooler'} ),
  ( ('MS_WIN_Services_Specific', 'Word2PDFService', {}), [], ['vword2pdf02x', 'vword2pdf01x'], {'description': u'Word2PDFService'} ),
  ( ('MS_WIN_Services_Specific', 'mirthdev', {}), [], ['vmirthdev01x'], {'description': u'Mirth Connect'} ),
  ( ('MS_WIN_Services_Specific', 'MososCsLauncher', {}), [], ['vmosos02x'], {'description': u'Mosos'} ),
  ( ('MS_WIN_Services_Specific', 'MSMQ', {}), [], ['voazistappl01x', 'voazistweb01x', 'bexchmail01a', 'bexchmail01b', 'glucosrv2', 'vaqure01x', 'vhif01x', 'vsophos01x', 'vuroflow01x', 'vnovanet01x', 'vevault02x', 'vbartender01x', 'sunifi01c', 'vhoneywebi01x', 'voazispappl01x', 'voazispweb01x'], {'description': u'Microsoft Message Queuing'} ),
  ( ('MS_WIN_Services_Specific', 'XListener', {}), [], ['voazistweb01x', 'voazispweb01x'], {'description': u'Oazis HL7'} ),
  ( ('MS_WIN_Services_Specific', 'SagaHcpsSyncService', {}), [], ['vsaga02x', 'vsagap01x'], {'description': u'Saga Sync Service AD'} ),
  ( ('MS_WIN_Services_Specific', 'AOS50*', {}), [], ['vsdworxacc02x', 'vsdworxprd02x', 'vsdworxprd03x'], {'description': u'Dynamics AX Object Server'} ),
  ( ('MS_WIN_Services_Specific', 'TOPdesk*', {}), [], ['vtopdeskit01x', 'vtopdeskit02x'], {'description': u'Topdesk IT'} ),
  ( ('MS_WIN_Services_Specific', 'Ultimo', {}), [], ['vultimodev01x', 'vultimoprod01x'], {'description': u'Ultimo'} ),
  ( ('MS_WIN_Services_Specific', 'alfrescoPostgreSQL', {}), [], ['vtestalf01x'], {'description': u'Alfresco'} ),
  ( ('MS_WIN_Services_Specific', 'ServerManagementGateway', {}), [], ['vwac01x'], {'description': u'Windows Admin Center'} ),
  ( ('MS_WIN_Services_Specific', 'GXMMM*', {}), [], ['vcvvsa03x', 'vcvvsa02x'], {'description': u'CommVault'} ),
  ( ('MS_WIN_Services_Specific', '3MCodingandReimbursementSystemServer', {}), [], ['v3mgrouper04x', 'v3mgrouper02x'], {'description': u'3M Coding and Reimbursement System Server'} ),
  ( ('MS_WIN_Services_Specific', 'TOPdeskhr', {}), [], ['vtopdeskhr01x'], {'description': u'Topdesk HR'} ),
  ( ('MS_WIN_Services_Specific', 'Automate_Schedule_Agent_Server', {}), [], ['vsky201601x'], {'description': u'Automate Schedule Agent Server (Skybot)'} ),
  ( ('MS_WIN_Services_Specific', 'ScanMail_', {'Service_name': ('ScanMail_(?!(RemoteConfig)).+',)}), [], ['bexchmail01a', 'bexchmail01b'], {'description': u'ScanMail for Microsoft Exchange'} ),
  ( ('MS_WIN_Services_Specific', 'MSSQL', {'Service_name': ('MSSQL.*(?!=WID)$',)}), [], ['bexchmail01a', 'bexchmail01b', 'vcvmain01x', 'vcvmain02x', 'vpads01x', 'vuroflow01x', 'vlicsrv01x', 'vblueidlm01x', 'vblueidsc01x', 'vbartender01x', 'vasist01x'], {'description': u'SQL Server'} ),
  ( ('MS_WIN_Services_Specific', 'IServerPlus', {}), [], ['vbrainrt01x'], {'comment': u'Brainlab RT HL7\n', 'description': u'IServerPlus'} ),
  ( ('MS_WIN_Services_Specific', 'hasplms', {}), [], ['vbrainrt01x', 'vcytosure01x', 'vois01x', 'vsmartnxt01x', 'vhxlm01x', 'vhxsc01x', 'v3mensio01x', 'vblueid01x', 'vblueidlm01x', 'vblueidsc01x', 'vphonexone01x'], {'description': u'Sentinel LDK License Manager'} ),
  ( ('MS_WIN_Services_Specific', 'GatewayProcessorService', {}), [], ['vinnereye01x'], {'description': u'Microsoft Radiomics Gateway Processor'} ),
  ( ('MS_WIN_Services_Specific', 'GatewayReceiveService', {}), [], ['vinnereye01x'], {'description': u'GatewayReceiveService'} ),
  ( ('MS_WIN_Services_Specific', 'Omixon_HLA_Twin_NG', {}), [], ['vhlatwin01x'], {'description': u'Omixon HLA Twin NG Server & Typer Server'} ),
  ( ('MS_WIN_Services_Specific', 'unified-messaging', {}), [], ['vmedimailacc01x', 'vmedimail02x'], {'description': u'unified-messaging (medimail)'} ),
  ( ('MS_WIN_Services_Specific', 'CSUpdate', {}), [], ['vtopaz01x'], {'description': u'Care Solutions Update Services'} ),
  ( ('MS_WIN_Services_Specific', 'WOServer', {}), [], ['vemergin02x'], {'description': u'Event Management Integration Service'} ),
  ( ('MS_WIN_Services_Specific', 'Event', {}), [], ['vemergin02x'], {'description': u'Event Services Emergin'} ),
  ( ('MS_WIN_Services_Specific', 'Apache', {}), [], ['vrochevcon01x', 'vnovanet01x', 'vmyqm01x', 'vmyqs01x', 'vmyqs02x', 'vkitry02x'], {'description': u'Apache'} ),
  ( ('MS_WIN_Services_Specific', 'Axeda', {}), [], ['vrochevcon01x', 'glucosrv2', 'vivsoft01x', 'variadb01x', 'vcitm01x'], {'description': u'Axeda Remote Control Servcies'} ),
  ( ('MS_WIN_Services_Specific', 'Cache_d-_intersystems_hsfoundation', {}), [], ['vrochevcon01x'], {'description': u'Cach\xe9 Roche'} ),
  ( ('MS_WIN_Services_Specific', 'HSFOUNDATION2015httpd', {}), [], ['vrochevcon01x'], {'description': u'HSFOUNDATION2015httpd Roche'} ),
  ( ('MS_WIN_Services_Specific', 'EyeStationImportService', {}), [], ['vwhiimport01x'], {'description': u'EyeStation Import Service OIS - IBM Watson Imaging coft'} ),
  ( ('MS_WIN_Services_Specific', 'xmlproc', {}), [], ['vwhiimport01x'], {'description': u'Merge XML Processing Service'} ),
  ( ('MS_WIN_Services_Specific', 'Besco_UpdateService', {}), [], ['vbesco01x'], {'description': u'Besco Update Service'} ),
  ( ('MS_WIN_Services_Specific', 'WnvHtmlToPdfWinService', {}), [], ['vwinnovative01x'], {'description': u'WnvHtmlToPdfWinService'} ),
  ( ('MS_WIN_Services_Specific', 'RingMaster', {}), [], ['vtraprm01x'], {'description': u'Trapeze RingMaster'} ),
  ( ('MS_WIN_Services_Specific', 'moodle', {}), [], ['vlmst01x'], {'description': u'Moodle apache & mysql'} ),
  ( ('MS_WIN_Services_Specific', 'Rhapsody', {}), [], ['vphilibe01x'], {'description': u'Rhapsody'} ),
  ( ('MS_WIN_Services_Specific', 'OracleIFA1TNSListener', {}), [], ['vgenemapper01x', 'vgenemapper02x', 'vgenemapper03x'], {'description': u'Oracle TNS Listener Genemapper'} ),
  ( ('MS_WIN_Services_Specific', 'OracleServiceIFA', {}), [], ['vgenemapper01x', 'vgenemapper02x', 'vgenemapper03x'], {'description': u'Oracle DB Genemapper'} ),
  ( ('MS_WIN_Services_Specific', 'ontapavc', {}), [], ['vscancdot01x', 'vscancdot02x', 'vscancdot03x', 'vscancdot04x'], {'description': u'ONTAP AV Connector (Sophos)'} ),
  ( ('MS_WIN_Services_Specific', 'Sophos_Anti-Virus_for_NetApp', {}), [], ['vscancdot01x', 'vscancdot02x', 'vscancdot03x', 'vscancdot04x'], {'description': u'Sophos Anti-Virus for NetApp'} ),
  ( ('MS_WIN_Services_Specific', 'BCAAA', {}), [], ['blueauthsrv', 'blueauthsrv2'], {'description': u'Authentication and Authorization Agent for Blue Coat Systems'} ),
  ( ('MS_WIN_Services_Specific', 'Tssdis', {}), [], ['vlegacybroker01x', 'vrdsbroker08x', 'vfacosrds01x', 'vlgenrds01x', 'vlabords01x', 'vhoneywrds01x', 'vhighlander02x', 'voazisrds01x', 'vrdsbroker1601x'], {'description': u'Remote Desktop Connection Broker'} ),
  ( ('MS_WIN_Services_Specific', 'DynCache', {}), [], ['vcvmain01x', 'vcvmain02x', 'scvmedia01b', 'vcvmedia01x'], {'description': u'Commvault DynCache service'} ),
  ( ('MS_WIN_Services_Specific', 'SQLAgent', {}), [], ['vcvmain01x', 'vcvmain02x'], {'description': u'SQL Server Agent (COMMVAULT)'} ),
  ( ('MS_WIN_Services_Specific', 'Gx', {}), [], ['vcvmain01x', 'scvmedia01b', 'vcvmedia01x', 'vcvvsa02x', 'vcvvsa03x'], {'description': u'CommVault Services'} ),
  ( ('MS_WIN_Services_Specific', 'CV', {}), [], ['vcvmain01x'], {'description': u'CommVault Services'} ),
  ( ('MS_WIN_Services_Specific', 'Instance002', {}), [], ['vcvmain02x'], {'description': u'Commvault Instance002'} ),
  ( ('MS_WIN_Services_Specific', 'GxMONGO', {}), [], ['vcvmain02x'], {'description': u'GxMONGO(Instance001)'} ),
  ( ('MS_WIN_Services_Specific', 'idsServer', {}), [], ['dzinesrv'], {'description': u'idsServer'} ),
  ( ('MS_WIN_Services_Specific', 'Sentinel', {}), [], ['dzinesrv', 'vlighthouse01x'], {'description': u'Sentinel Services'} ),
  ( ('MS_WIN_Services_Specific', 'NTDS', {}), [], ['dcuzb1', 'dcuzb2'], {'disabled': True, 'description': u'Active Directory Domain Services'} ),
  ( ('MS_WIN_Services_Specific', 'ADWS', {}), [], ['view01x', 'view02x', 'vcentervdi01x'], {'description': u'Active Directory Web Services'} ),
  ( ('MS_WIN_Services_Specific', 'Dfs', {}), [], ['vdfs01x'], {'description': u'DFS Services'} ),
  ( ('MS_WIN_Services_Specific', 'Gx', {}), [], ['bqlik01b', 'slpm01b', 'vheyex01x', 'sunifi01c', 'vwinguard01x'], {'description': u'CommVault Backup Client Services'} ),
  ( ('MS_WIN_Services_Specific', 'IV', {}), [], ['imgvaultuzb'], {'description': u'GE Image Vault Service'} ),
  ( ('MS_WIN_Services_Specific', 'ASANY', {}), [], ['imgvaultuzb', 'vrenalsoft01x'], {'description': u'daptive Server Anywhere'} ),
  ( ('MS_WIN_Services_Specific', 'RDCMService', {}), [], ['imgvaultuzb'], {'description': u'GE Vivid Image PDP processing Module'} ),
  ( ('MS_WIN_Services_Specific', 'TAO', {}), [], ['imgvaultuzb'], {'description': u'TAO Implementation Repository'} ),
  ( ('MS_WIN_Services_Specific', 'CSZapp', {}), [], ['vtopaz01x'], {'description': u'Care Solutions Zapp Service'} ),
  ( ('MS_WIN_Services_Specific', 'MyAlfresco', {}), [], ['alfrescoprodsrv'], {'description': u'Alfresco Vergaderbeheer'} ),
  ( ('MS_WIN_Services_Specific', 'alfrescoTomcatnum1', {}), [], ['alfrescoprodsrv'], {'description': u'Alfresco Labo Guide & Brieven'} ),
  ( ('MS_WIN_Services_Specific', 'Qlik', {}), [], ['bqlik01b', 'vqlikprint01x'], {'description': u'Qlik Sense Services'} ),
  ( ('MS_WIN_Services_Specific', 'Schedule', {}), [], ['bsqlpcognos01a', 'vsqltcognos01x', 'useradmsrv', 'vnicview01x', 'vnicview02x', 'vpads01x', 'vseqnext01x', 'vget01x', 'vehr01x', 'vbrief01x', 'valfmedp01x', 'vtimestamp01x', 'vbrestonica01x', 'vnicview01x', 'vnicview02x'], {'description': u'Windows Scheduler'} ),
  ( ('MS_WIN_Services_Specific', 'Word2PDFService', {}), [], ['extsysclt01'], {'description': u'Word2PDFService'} ),
  ( ('MS_WIN_Services_Specific', 'cobas', {}), [], ['glucosrv2'], {'description': u'Roche Cobas 1000 Services'} ),
  ( ('MS_WIN_Services_Specific', 'PCommunicator', {}), [], ['glucosrv2'], {'description': u'Roche Cobas 1000 PCommunicator'} ),
  ( ('MS_WIN_Services_Specific', 'Redis', {}), [], ['glucosrv2'], {'description': u'Roche Cobas 1000 Redis Server Service'} ),
  ( ('MS_WIN_Services_Specific', 'Roche_Utility', {}), [], ['glucosrv2'], {'description': u'Roche Cobas 1000 Utility'} ),
  ( ('MS_WIN_Services_Specific', 'CIT1K64httpd', {}), [], ['glucosrv2'], {'description': u'Roche Cobas 1000 Web Server for CIT1K64'} ),
  ( ('MS_WIN_Services_Specific', 'Cache_d-_cobasit1000_cache', {}), [], ['glucosrv2'], {'description': u'Cach\xe9 DB Roche Cobas 1000'} ),
  ( ('MS_WIN_Services_Specific', 'MV_Device_Server', {}), [], ['imdapplsrv'], {'description': u'IMDSoft'} ),
  ( ('MS_WIN_Services_Specific', 'MV_EventTriggering', {}), [], ['imdapplsrv'], {'description': u'IMDSoft'} ),
  ( ('MS_WIN_Services_Specific', 'MV_Generic_ADT', {}), [], ['imdapplsrv'], {'description': u'IMDSoft'} ),
  ( ('MS_WIN_Services_Specific', 'MV_PICU', {}), [], ['imdapplsrv'], {'description': u'IMDSoft'} ),
  ( ('MS_WIN_Services_Specific', 'MV_PrintServer', {}), [], ['imdapplsrv'], {'description': u'IMDSoft'} ),
  ( ('MS_WIN_Services_Specific', 'MV_PRODLABS', {}), [], ['imdapplsrv'], {'description': u'IMDSoft'} ),
  ( ('MS_WIN_Services_Specific', 'VsfSvr', {}), [], ['infinitygwsrv'], {'description': u'Dr\xe4ger Infinity Gateway'} ),
  ( ('MS_WIN_Services_Specific', 'WvGw', {}), [], ['infinitygwsrv'], {'description': u'Dr\xe4ger Infinity Gateway'} ),
  ( ('MS_WIN_Services_Specific', 'ITNextelService', {}), [], ['itranssrv'], {'description': u'ITNextelService Dect'} ),
  ( ('MS_WIN_Services_Specific', 'mvf', {}), [], ['pacsweb012456'], {'description': u'Agfa PacsWeb DICOM Services'} ),
  ( ('MS_WIN_Services_Specific', 'autopilot', {}), [], ['pacsweb012456'], {'description': u'Agfa PacsWeb DICOM Services'} ),
  ( ('MS_WIN_Services_Specific', 'curator', {}), [], ['pacsweb012456'], {'description': u'Agfa PacsWeb Exhibit Curator'} ),
  ( ('MS_WIN_Services_Specific', 'ExhibServer', {}), [], ['pacsweb012456'], {'description': u'Agfa PacsWeb ExhibServer'} ),
  ( ('MS_WIN_Services_Specific', 'mcfload', {}), [], ['pacsweb012456'], {'description': u'Agfa Pacsweb mcfload'} ),
  ( ('MS_WIN_Services_Specific', 'PACS', {}), [], ['pacsweb012456'], {'description': u'Agfa PacsWeb PACS Client Updater'} ),
  ( ('MS_WIN_Services_Specific', 'Rhapsody_6', {}), [], ['rhapsodywin'], {'description': u'Rhapsody 6'} ),
  ( ('MS_WIN_Services_Specific', 'SmartPass', {}), [], ['trapspsrv'], {'description': u'Trapeze SmartPass'} ),
  ( ('MS_WIN_Services_Specific', 'FreeSSHDService', {}), [], ['useradmsrv'], {'description': u'FreeSSH Windows'} ),
  ( ('MS_WIN_Services_Specific', 'SAP_DCP_Server_2', {}), [], ['useradmsrv'], {'description': u'SAP - MSSQL Connect'} ),
  ( ('MS_WIN_Services_Specific', 'CertSvc', {}), [], ['uzlicsrv', 'vica01x'], {'description': u'Active Directory Certificate Services'} ),
  ( ('MS_WIN_Services_Specific', 'AutoCAD', {}), [], ['uzlicsrv'], {'description': u'AutoCAD License Server'} ),
  ( ('MS_WIN_Services_Specific', 'alfrescoTomcat', {'Service_name': ('alfrescoTomcat(?!(.+))',)}), [], ['valfmedt01x', 'valfmedp01x'], {'description': u'Alfresco Tomcat'} ),
  ( ('MS_WIN_Services_Specific', 'tomcat6', {}), [], ['vtestalf01x'], {'description': u'Alfresco Tomcat Vergaderbeheer'} ),
  ( ('MS_WIN_Services_Specific', 'Valab', {}), [], ['vvalab01x'], {'description': u'Valab Services'} ),
  ( ('MS_WIN_Services_Specific', 'VALAB', {}), [], ['vvalab01x'], {'description': u'Valab'} ),
  ( ('MS_WIN_Services_Specific', 'MSExchange', {'Service_name': ('MSExchange(?!(POP3BE|Pop3|NotificationsBroker)).+',)}), [], ['bexchmail01a', 'bexchmail01b'], {'description': u'MSExchange Services'} ),
  ( ('MS_WIN_Services_Specific', 'HostControllerService', {}), [], ['bexchmail01a', 'bexchmail01b'], {'description': u'Microsoft Exchange Search Host Controller'} ),
  ( ('MS_WIN_Services_Specific', 'Othello_', {'Service_name': ('Othello_(?!((Test|NewVs)_DbCleanUp)).+',)}), [], ['vothello03x'], {'description': u'Othello Services'} ),
  ( ('MS_WIN_Services_Specific', 'Othello_', {'Service_name': ('Othello_(?!((Prod|NewVs)_DbCleanUp)).+',)}), [], ['vothello01x'], {'description': u'Othello Services'} ),
  ( ('MS_WIN_Services_Specific', 'Radiometer_AQURE_', {'Service_name': ('Radiometer_AQURE_(?!((SNMP)_agent)).+',)}), [], ['vaqure01x'], {'description': u'Radiometer Aqure Services'} ),
  ( ('MS_WIN_Services_Specific', 'Mirth', {}), [], ['vaqure01x', 'vsmartnxt01x', 'vmirth01x', 'vmuseapp01x'], {'description': u'Mirth'} ),
  ( ('MS_WIN_Services_Specific', 'Virtual_Digipass_MDC', {}), [], ['vascosrv'], {'description': u'Vasco Digipass'} ),
  ( ('MS_WIN_Services_Specific', 'MiSeqReporter', {}), [], ['vhighlander01x'], {'disabled': True, 'description': u'MiSeqReporter Genetica'} ),
  ( ('MS_WIN_Services_Specific', 'seqsphereserver', {}), [], ['vseqsphere01x'], {'description': u'SeqSphere+ Service LMIK'} ),
  ( ('MS_WIN_Services_Specific', 'GBOS', {}), [], ['vgbos01x'], {'description': u'GBOS service'} ),
  ( ('MS_WIN_Services_Specific', 'ws', {'Service_name': ('^ws(?!((Browser))).+',)}), [], ['view01x', 'view02x'], {'description': u'View Services'} ),
  ( ('MS_WIN_Services_Specific', 'ADAM_VMware', {}), [], ['view01x', 'view02x', 'vcentervdi01x'], {'description': u'VMware View LDAP directory services.'} ),
  ( ('MS_WIN_Services_Specific', 'StatusManagementService', {}), [], ['vnicview01x'], {'description': u'NicView'} ),
  ( ('MS_WIN_Services_Specific', 'DICOM', {}), [], ['vhif01x', 'vforum01x'], {'description': u'DICOM Service'} ),
  ( ('MS_WIN_Services_Specific', 'Philips', {}), [], ['vhif01x'], {'description': u'Philips Services'} ),
  ( ('MS_WIN_Services_Specific', '^IV', {}), [], ['vivsoft01x'] ),
  ( ('MS_WIN_Services_Specific', 'SrvPrintBrwsr', {}), [], ['vivsoft01x'], {'description': u'MEDarchiver - Print Browser'} ),
  ( ('MS_WIN_Services_Specific', 'Oracle', {'Service_name': ('Oracle(?!(JobSchedulerMASTER)).+',)}), [], ['vivsoft01x'], {'description': u'Oracle database services'} ),
  ( ('MS_WIN_Services_Specific', 'Nutriscript', {}), [], ['vnutrisrv01x'], {'description': u'Nutriscript Services'} ),
  ( ('MS_WIN_Services_Specific', 'DgAwEncx', {}), [], ['vois01x', 'vheyex01x', 'v3mensio01x', 'vbionumerics01x', 'vlighthouse01x'], {'description': u'Digi USB Anywhere Hub'} ),
  ( ('MS_WIN_Services_Specific', 'VideoManagerService', {}), [], ['vois01x'], {'description': u'Symphony OIS Service'} ),
  ( ('MS_WIN_Services_Specific', 'SymphonyDBsync', {}), [], ['vois01x'], {'description': u'Symphony OIS Service'} ),
  ( ('MS_WIN_Services_Specific', 'DicomManagerService', {}), [], ['vois01x'], {'description': u'Symphony OIS service'} ),
  ( ('MS_WIN_Services_Specific', 'PADS4', {}), [], ['vpads01x'], {'description': u'PADS services'} ),
  ( ('MS_WIN_Services_Specific', 'BIS_JCC_Connector', {}), [], ['vpads01x'], {'description': u'PADS BIS services'} ),
  ( ('MS_WIN_Services_Specific', 'ACIndexImporter', {}), [], ['vscanview01x'], {'description': u'Scanview Service'} ),
  ( ('MS_WIN_Services_Specific', 'acdmssrv', {}), [], ['vscanview01x'], {'description': u'Scanview Service'} ),
  ( ('MS_WIN_Services_Specific', 'AI_UPDATE_SERVICE_POINT', {}), [], ['vsccm01x', 'vsccm02x'], {'description': u'SMS Configuration Manager Site Role'} ),
  ( ('MS_WIN_Services_Specific', 'CcmExec', {}), [], ['vsccm01x', 'vsccm02x'], {'description': u'SMS Agent Host'} ),
  ( ('MS_WIN_Services_Specific', 'CmRcService', {}), [], ['vsccm01x'], {'description': u'SMS Configuration Manager Remote Control'} ),
  ( ('MS_WIN_Services_Specific', 'SMS_', {'Service_name': ('SMS_(?!(.*SITE_BACKUP|SITE_SQL_BACKUP_VSCCM02X.UZBRUSSEL.BE))',)}), [], ['vsccm01x', 'vsccm02x', 'vsccmsql02x'], {'description': u'SMS Services'} ),
  ( ('MS_WIN_Services_Specific', 'WsusService', {}), [], ['vsccm01x', 'vsccm02x'], {'description': u'SMS WSUS Update manager'} ),
  ( ('MS_WIN_Services_Specific', 'WDSServer', {}), [], ['vsccm01x', 'vsccm02x'], {'description': u'SMS Windows Deployment Services Server'} ),
  ( ('MS_WIN_Services_Specific', 'WSusCertServer', {}), [], ['vsccm01x'], {'description': u'SMS WSUS Certificate Server'} ),
  ( ('MS_WIN_Services_Specific', 'Cis', {}), [], ['vsmartnxt01x'], {'description': u'Acertys Sentry Services'} ),
  ( ('MS_WIN_Services_Specific', 'MsDtsServer', {}), [], ['vsmartnxt01x', 'vcentervdi01x', 'vauradb01x', 'variadb01x'], {'description': u'SQL Server Integration Services'} ),
  ( ('MS_WIN_Services_Specific', 'Sentry_CIS_Reverse_Proxy', {}), [], ['vsmartnxt01x'], {'description': u'Acertys Sentry Services'} ),
  ( ('MS_WIN_Services_Specific', 'MobileDataService', {}), [], ['vsmartnxt01x'], {'description': u'Acertys Sentry Services'} ),
  ( ('MS_WIN_Services_Specific', 'VASDATASERVICE', {}), [], ['vsmartnxt01x'], {'description': u'Acertys Sentry Services'} ),
  ( ('MS_WIN_Services_Specific', 'SENTRYSUITE', {}), [], ['vsmartnxt01x'], {'description': u'Acertys SentrySuite SQL Services'} ),
  ( ('MS_WIN_Services_Specific', 'MAS', {}), [], ['vsteril01x'], {'description': u'MAS Steril Aexis'} ),
  ( ('MS_WIN_Services_Specific', 'MLINE_COMBOX', {}), [], ['vsteril01x'], {'description': u'MLINE steril Aexis'} ),
  ( ('MS_WIN_Services_Specific', 'OracleMTS', {}), [], ['vsteril01x', 'slpm01a', 'slpm01b'], {'description': u'OracleMTSRecoveryService'} ),
  ( ('MS_WIN_Services_Specific', 'OracleOraDb11g_home1TNSListener', {}), [], ['vsteril01x', 'slpm01a', 'slpm01b'], {'description': u'Oracle 11 DB Service'} ),
  ( ('MS_WIN_Services_Specific', 'OracleService', {}), [], ['vsteril01x', 'slpm01a', 'slpm01b', 'vcitm01x'], {'description': u'OracleService'} ),
  ( ('MS_WIN_Services_Specific', 'SpeechExec_Enterprise_License_Server_Service', {}), [], ['vmdidisrv', 'vextsys01x'], {'description': u'Philips SpeechExec Enterprise License Server Service'} ),
  ( ('MS_WIN_Services_Specific', 'ssotomcat', {}), [], ['vcentervdi01x'], {'description': u'vCenter Single Sign On'} ),
  ( ('MS_WIN_Services_Specific', 'vimQueryService', {}), [], ['vcentervdi01x'], {'description': u'VMware vCenter Inventory Service'} ),
  ( ('MS_WIN_Services_Specific', 'svid', {}), [], ['vcentervdi01x'], {'description': u'VMware View Composer'} ),
  ( ('MS_WIN_Services_Specific', 'vctomcat', {}), [], ['vcentervdi01x'], {'description': u'VMware VirtualCenter Management Webservices'} ),
  ( ('MS_WIN_Services_Specific', 'vpxd', {}), [], ['vcentervdi01x'], {'description': u'VMware VirtualCenter Server'} ),
  ( ('MS_WIN_Services_Specific', 'vmware-ufad-vci', {}), [], ['vcentervdi01x'], {'description': u'VMware vSphere Update Manager Service'} ),
  ( ('MS_WIN_Services_Specific', 'SUM', {}), [], ['vsophos01x'], {'description': u'Sophos Update Manager'} ),
  ( ('MS_WIN_Services_Specific', 'MSSQL$SOPHOS', {}), [], ['vsophos01x'], {'disabled': True, 'description': u'MS SQL Sophos'} ),
  ( ('MS_WIN_Services_Specific', 'SYMPREX', {}), [], ['vsymprex01x'], {'description': u'Symprex services'} ),
  ( ('MS_WIN_Services_Specific', 'iListDTE', {}), [], ['vuroflow01x'], {'description': u'Uroflow service'} ),
  ( ('MS_WIN_Services_Specific', 'Advantage', {}), [], ['vsirscan01x'], {'description': u'Advantage Database Server'} ),
  ( ('MS_WIN_Services_Specific', 'ftpsvc', {}), [], ['vsirscan01x'], {'description': u'Microsoft IIS FTP server'} ),
  ( ('MS_WIN_Services_Specific', 'Sirius', {}), [], ['vsirius01x'], {'description': u'Sirius Services'} ),
  ( ('MS_WIN_Services_Specific', 'STConsoleSvc', {}), [], ['vshavlik01x'], {'description': u'Shavlik console serive'} ),
  ( ('MS_WIN_Services_Specific', 'jsiService', {}), [], ['vseqnext01x', 'vseqpilot01x'], {'description': u'SeqNext & SeqPilote Service'} ),
  ( ('MS_WIN_Services_Specific', 'PostgreSql', {}), [], ['vseca01x'], {'description': u'PostgreSql DB'} ),
  ( ('MS_WIN_Services_Specific', 'seca', {}), [], ['vseca01x'], {'description': u'seca services'} ),
  ( ('MS_WIN_Services_Specific', 'ClsServer', {}), [], ['vseca01x'], {'description': u'Seca Communication and License Server'} ),
  ( ('MS_WIN_Services_Specific', 'DbBackup', {}), [], ['vseca01x'], {'description': u'seca database backup'} ),
  ( ('MS_WIN_Services_Specific', 'TWKSCARDSRV', {}), [], ['vrenalsoft01x'], {'description': u'Baxter Renalsoft CHIPDRIVE SCARD Service'} ),
  ( ('MS_WIN_Services_Specific', 'LPDSVC', {}), [], ['vprint01x', 'vprint02x'], {'description': u'Line Printer Daemon (LPD) servic'} ),
  ( ('MS_WIN_Services_Specific', 'printermonsvc', {}), [], ['vprint01x'], {'description': u'UZB Print Monitor'} ),
  ( ('MS_WIN_Services_Specific', 'SAPSprint', {}), [], ['vprint01x', 'vprint02x'], {'description': u'SAP Print Service'} ),
  ( ('MS_WIN_Services_Specific', 'RTM', {}), [], ['vnovanet01x'], {'description': u'NovaBiomedical Servcies'} ),
  ( ('MS_WIN_Services_Specific', 'SQLANY', {}), [], ['vnovanet01x', 'voazispappl02x'], {'description': u'SQL Anywhere Novanet'} ),
  ( ('MS_WIN_Services_Specific', 'Firebird', {}), [], ['vmyqm01x', 'vmyqs01x', 'vmyqs02x'], {'description': u'MyQ Firebird Database Server'} ),
  ( ('MS_WIN_Services_Specific', 'KNM_PM', {}), [], ['vmyqm01x', 'vmyqs01x', 'vmyqs02x'], {'description': u'KYOCERA Net Manager Server'} ),
  ( ('MS_WIN_Services_Specific', 'MyQ', {}), [], ['vmyqm01x', 'vmyqs01x', 'vmyqs02x'], {'description': u'MyQ - Receives and prints print jobs'} ),
  ( ('MS_WIN_Services_Specific', 'myq_svc', {}), [], ['vmyqm01x', 'vmyqs01x', 'vmyqs02x'], {'description': u'MyQ : Manages service contracts and orders.'} ),
  ( ('MS_WIN_Services_Specific', 'Printer_DCA', {}), [], ['vmyqm01x'], {'description': u'MyQ Printer DCA'} ),
  ( ('MS_WIN_Services_Specific', 'Acquisition', {}), [], ['vmosos01x'], {'description': u'Mosos CTG Acquisition'} ),
  ( ('MS_WIN_Services_Specific', 'MososCS', {}), [], ['vmosos01x'], {'description': u'Mosos Communication Server'} ),
  ( ('MS_WIN_Services_Specific', 'MIM', {}), [], ['vmim01x'], {'description': u'MIM Services'} ),
  ( ('MS_WIN_Services_Specific', 'JIRA', {}), [], ['vjira01x'], {'description': u'Jira Service'} ),
  ( ('MS_WIN_Services_Specific', 'TermServLicensing', {}), [], ['vlicense01x'], {'description': u'Remote Desktop Licensing'} ),
  ( ('MS_WIN_Services_Specific', 'postgres_uzbot', {}), [], ['vkwsmon01x'], {'description': u'uzbot postgres DB'} ),
  ( ('MS_WIN_Services_Specific', 'HPRSMAIN', {}), [], ['virshp01x'], {'description': u'HP Insight Remote Support'} ),
  ( ('MS_WIN_Services_Specific', 'HPRSRECEIVERS', {}), [], ['virshp01x'], {'description': u'HP Insight RS Event Receiver'} ),
  ( ('MS_WIN_Services_Specific', 'Wildfly', {}), [], ['vigp01x', 'vhemohub01x'], {'description': u'Wildfly (jboss) Service'} ),
  ( ('MS_WIN_Services_Specific', 'postgresql', {}), [], ['vigp01x'], {'description': u'PostgreSQL DB'} ),
  ( ('MS_WIN_Services_Specific', 'HELICSVC', {}), [], ['vheyex01x'], {'description': u'Heidelberg Eye Explorer License Manager'} ),
  ( ('MS_WIN_Services_Specific', 'H2DatabaseService', {}), [], ['vhms01x'], {'description': u'H2 Database Engine Service'} ),
  ( ('MS_WIN_Services_Specific', 'OracleOraDB12Home1TNSListener', {}), [], ['vhemohub01x', 'vkitry01x'], {'description': u'Oracle 12 DB Service'} ),
  ( ('MS_WIN_Services_Specific', 'OracleService', {}), [], ['vhemohub01x', 'vkitry01x'], {'description': u'Oracle DB 12 Service'} ),
  ( ('MS_WIN_Services_Specific', 'MultiOnline', {}), [], ['vhemohub01x'], {'description': u'Cobas8000 : Multionline LIS BF'} ),
  ( ('MS_WIN_Services_Specific', 'tomcat', {}), [], ['vhd4dp01x'], {'description': u'tomcat'} ),
  ( ('MS_WIN_Services_Specific', 'Xtremis', {}), [], ['vget01x'], {'description': u'Xtremis Get Service'} ),
  ( ('MS_WIN_Services_Specific', 'sv_', {}), [], ['vget01x', 'vgetna01x'], {'description': u'Get Services'} ),
  ( ('MS_WIN_Services_Specific', 'DB2DAS00', {}), [], ['vget01x'], {'description': u'DB2 DB Services'} ),
  ( ('MS_WIN_Services_Specific', 'DB2MGMTSVC', {}), [], ['vget01x'], {'description': u'DB2 DB Services'} ),
  ( ('MS_WIN_Services_Specific', 'DB2REMOTECMD', {}), [], ['vget01x'], {'description': u'DB2 DB Services'} ),
  ( ('MS_WIN_Services_Specific', 'EnterpriseVault', {}), [], ['vevault02x'], {'description': u'EnterpriseVault Services'} ),
  ( ('MS_WIN_Services_Specific', 'MCAFEE', {}), [], ['vepo01x'], {'description': u'McAfee Services'} ),
  ( ('MS_WIN_Services_Specific', 'Epimed', {}), [], ['vepimed01x'], {'description': u'Epimed Gateway Service'} ),
  ( ('MS_WIN_Services_Specific', '3mensio', {}), [], ['v3mensio01x'], {'description': u'3mensio Service'} ),
  ( ('MS_WIN_Services_Specific', 'DIABSCAN', {}), [], ['vdiabscan01x'], {'description': u'Diabscan Services'} ),
  ( ('MS_WIN_Services_Specific', 'CDataService', {}), [], ['vchiptexlct01x'], {'description': u'Chiptex Service'} ),
  ( ('MS_WIN_Services_Specific', 'BlueFuse', {}), [], ['vbluefuse01x'], {'description': u'BlueFuse Service'} ),
  ( ('MS_WIN_Services_Specific', 'BarTender', {}), [], ['vbartender01x'], {'description': u'BarTender Services'} ),
  ( ('MS_WIN_Services_Specific', 'Seagull', {}), [], ['vbartender01x'], {'description': u'Seagull License Server'} ),
  ( ('MS_WIN_Services_Specific', 'Maestro', {}), [], ['vbartender01x'], {'description': u'Bartender Maestro Printer Server'} ),
  ( ('MS_WIN_Services_Specific', 'Nw(?!(DataClassificationSvc)).+', {}), [], ['vaudit01x'], {'description': u'Netwrix Services'} ),
  ( ('MS_WIN_Services_Specific', 'FscrAgent', {}), [], ['vaudit01x'], {'description': u'Netwrix Auditor for File Servers Compression Service'} ),
  ( ('MS_WIN_Services_Specific', 'uavrsvc', {}), [], ['vaudit01x'], {'description': u'Netwrix Auditor User Activity Core Service'} ),
  ( ('MS_WIN_Services_Specific', 'WscrAgent', {}), [], ['vaudit01x'], {'description': u'NetWrix Windows Server Change Reporter Agent'} ),
  ( ('MS_WIN_Services_Specific', 'Varian', {}), [], ['vauradb01x', 'variadb01x', 'variaweb01x'], {'description': u'Varian Services'} ),
  ( ('MS_WIN_Services_Specific', 'vmsdicom', {}), [], ['variadb01x'], {'description': u'Varian VMS Services'} ),
  ( ('MS_WIN_Services_Specific', 'VCDistributor', {}), [], ['variadb01x'], {'description': u'Varian Distributed Calculation Framework'} ),
  ( ('MS_WIN_Services_Specific', 'FileMonitor', {}), [], ['variaweb01x'], {'description': u'Varian File Monitor Service'} ),
  ( ('MS_WIN_Services_Specific', 'Waters', {}), [], ['sunifi01c'], {'description': u'Waters Services'} ),
  ( ('MS_WIN_Services_Specific', 'WatServiceHost', {}), [], ['sunifi01c'], {'description': u'Waters Service Host'} ),
  ( ('MS_WIN_Services_Specific', 'OracleASM', {}), [], ['sunifi01c'], {'description': u'Waters Unifi Oracle Services'} ),
  ( ('MS_WIN_Services_Specific', 'OracleOHService', {}), [], ['sunifi01c'], {'description': u'Waters Unifi Oracle Service'} ),
  ( ('MS_WIN_Services_Specific', 'OracleServiceUNIFI', {}), [], ['sunifi01c'], {'description': u'Waters Unifi Oracle Service'} ),
  ( ('MS_WIN_Services_Specific', 'HSCSERVER', {}), [], ['vhoneywebi01x'], {'description': u'Honeywell EBI HSCSERVER Services'} ),
  ( ('MS_WIN_Services_Specific', 'BacNet', {}), [], ['vhoneywebi01x'], {'description': u'Honeywell BacNet'} ),
  ( ('MS_WIN_Services_Specific', 'BACstac', {}), [], ['vhoneywebi01x'], {'description': u'HoneyWell BACnet'} ),
  ( ('MS_WIN_Services_Specific', 'LnsMtsSvc', {}), [], ['vhoneywebi01x'], {'description': u'HoneyWell support services to Echelon products in Microsoft Terminal Services (MTS) environments'} ),
  ( ('MS_WIN_Services_Specific', 'EXCEL_5000_Direct', {}), [], ['vhoneywebi01x'], {'description': u'HoneyWell Direct access to EXCEL 5000 controllers.'} ),
  ( ('MS_WIN_Services_Specific', 'GSDownloadManager', {}), [], ['vhoneywebi01x'], {'description': u'Download Manager Service for Honeywell Global Schedules'} ),
  ( ('MS_WIN_Services_Specific', 'EBIEventSrvc', {}), [], ['vhoneywebi01x'], {'description': u'HoneyWell EBI Alarm'} ),
  ( ('MS_WIN_Services_Specific', 'Honeywell', {}), [], ['vhoneywebi01x'], {'description': u'Honeywell Realtime Data Services Host'} ),
  ( ('MS_WIN_Services_Specific', 'HscOpciEngine', {}), [], ['vhoneywebi01x'], {'description': u'Honeywell Server OPC Data Transfer'} ),
  ( ('MS_WIN_Services_Specific', 'RDFStore', {}), [], ['vhoneywebi01x'], {'description': u'Honeywell Server RDF Store'} ),
  ( ('MS_WIN_Services_Specific', 'Remote_Sync_Server', {}), [], ['vhoneywebi01x'], {'description': u'honeyWell Remote Sync Server'} ),
  ( ('MS_WIN_Services_Specific', 'MSSQLServerOLAPService', {}), [], ['vhoneywebi01x'], {'description': u'SQL Server Analysis Services (MSSQLSERVER)'} ),
  ( ('MS_WIN_Services_Specific', 'Astraia', {}), [], ['vastraia01x'], {'description': u'Astraia Services'} ),
  ( ('MS_WIN_Services_Specific', 'RecordUpdateServer', {}), [], ['vastraia01x'], {'description': u'Astraia RecordUpdateServer'} ),
  ( ('MS_WIN_Services_Specific', 'Firebird', {}), [], ['vbiognost01x'], {'description': u'Firebird Services'} ),
  ( ('MS_WIN_Services_Specific', 'MUSE_', {}), [], ['vmuseapp01x'], {'description': u'Muse services'} ),
  ( ('MS_WIN_Services_Specific', 'apache', {}), [], ['vmuseapp01x'], {'description': u'apache server'} ),
  ( ('MS_WIN_Services_Specific', 'PhonEXONE4', {}), [], ['vphonexone01x'], {'description': u'PhoneXOne Services'} ),
  ( ('MS_WIN_Services_Specific', 'AGFA', {}), [], ['vxero8csp02x'], {'description': u'AGFA CSP Services'} ),
  ( ('MS_WIN_Services_Specific', 'IMPAX', {}), [], ['vxero8csp02x'], {'description': u'IMPAX CSP Service'} ),
  ( ('MS_WIN_Services_Specific', 'X-Elevator', {}), [], ['vbrestonica01x'], {'description': u'Brestonica X-Elevator'} ),
  ( ('MS_WIN_Services_Specific', 'OracleOraDB12Home1MTSRecoveryService', {}), [], ['vkitry01x'], {'description': u'Oracle DB Service Kitry'} ),
  ( ('MS_WIN_Services_Specific', 'MMS', {}), [], ['vacronis01x'], {'description': u'Acronis Managed Machine Service'} ),
  ( ('MS_WIN_Services_Specific', 'AMS', {}), [], ['vacronis01x'], {'description': u'Acronis Management Server Service'} ),
  ( ('MS_WIN_Services_Specific', 'Acronis', {'Service_name': ('Acronis(?!(ActiveProtectionService|_VSS_Provider)).+',)}), [], ['vacronis01x'], {'comment': u'ActiveProtectionService\n', 'description': u'Acronis Services'} ),
  ( ('MS_WIN_Services_Specific', 'ARSM', {}), [], ['vacronis01x'], {'description': u'Acronis Removable Storage Management Service'} ),
  ( ('MS_WIN_Services_Specific', 'AcrSch2Svc', {}), [], ['vacronis01x'], {'description': u'Acronis Scheduler2 Service'} ),
  ( ('MS_WIN_Services_Specific', 'ASM', {}), [], ['vacronis01x'], {'description': u'Acronis Service Manager Service'} ),
  ( ('MS_WIN_Services_Specific', 'UniversalInventory', {}), [], ['vasist01x'], {'description': u'Universal Inventory service'} ),
  ( ('MS_WIN_Services_Specific', 'CpiService', {}), [], ['vcitm01x'], {'description': u'cobas IT customer product inventory'} ),
  ( ('MS_WIN_Services_Specific', 'Data_Distribution_Client_Standalone_Service', {}), [], ['vcitm01x'], {'description': u'cobas IT middleware data distribution client'} ),
  ( ('MS_WIN_Services_Specific', 'Teleservice_Network_Agent', {}), [], ['vcitm01x'], {'description': u'Cobas8000 : Teleservice Network Agent'} ),
  ( ('MS_WIN_Services_Specific', 'LISA', {}), [], ['vcitm01x'], {'description': u'Cobos8000 LISA'} ),
  ( ('MS_WIN_Services_Specific', 'Fresco', {}), [], ['vdavinci01x'], {'description': u'Davinci Fresco Broker Service Vantage'} ),
  ( ('MS_WIN_Services_Specific', 'MIPS', {'Service_name': ('MIPS_(?!(CHL7_Dispatcher_UZBR_TEST)).+',)}), [], ['vdavinci01x', 'vdavincit01x'], {'description': u'Davinci MIPS'} ),
  ( ('MS_WIN_Services_Specific', 'Remote_Dongle_Service', {}), [], ['veplan01x'], {'description': u'Eplan Remote Dongle Service'} ),
  ( ('MS_WIN_Services_Specific', 'CZM', {}), [], ['vforum01x', 'vforumdev01x'], {'description': u'Zeiss Forum Services'} ),
  ( ('MS_WIN_Services_Specific', 'InfolandUserSynchronisation', {}), [], ['viprovaappl01x'], {'description': u'InfolandUserSynchronisation Service'} ),
  ( ('MS_WIN_Services_Specific', 'WinGuard', {}), [], ['vwinguard01x'], {'disabled': True, 'description': u'WinGuard Service'} ),
  ( ('MS_WIN_Services_Specific', 'npsrcsvr', {}), [], ['vwinguard01x'], {'description': u'NPort Secure Service'} ),
  ( ('MS_WIN_Services_Specific', 'TDOC', {}), [], ['vtdoc01x'], {'description': u'TDOC Services'} ),
  ( ('MS_WIN_Services_Specific', 'ServiceSOZO', {}), [], ['vsozo01x'], {'description': u'SOZO Services'} ),
  ( ('MS_WIN_Services_Specific', 'XMaintenance', {}), [], ['voazispappl01x', 'voazistappl01x', 'voazispweb01x'], {'description': u'Oazis Xmaintenance'} ),
  ( ('MS_WIN_Services_Specific', 'BOEXI40', {'Service_name': ('BOEXI40(?!(BWPublisherService)).+',)}), [], ['voazispappl02x'], {'comment': u'BWPublisherService\n', 'description': u'Business Objects'} ),
  ( ('MS_WIN_Services_Specific', 'SVNSubversion', {}), [], ['voazispappl02x'], {'description': u'Oazis LCMSubversion'} ),
  ( ('MS_WIN_Services_Specific', 'XGateway', {}), [], ['voazispweb01x'], {'description': u'Oazis XGateway'} ),
  ( ('MS_WIN_Services_Specific', 'XHL7', {}), [], ['voazispweb01x', 'voazistweb01x'], {'description': u'Oazis HL7'} ),
  ( ('MS_WIN_Services_Specific', 'XScheduler', {}), [], ['voazispweb01x', 'voazistweb01x'], {'description': u'Oazis XScheduler'} ),
  ( ('MS_WIN_Services_Specific', 'XTomcat', {}), [], ['voazispweb01x'], {'description': u'Oazis Xtomcat'} ),
  ( ('MS_WIN_Services_Specific', 'XURouter', {}), [], ['voazispweb01x', 'voazistweb01x'], {'description': u'Oazis XURouter'} ),
  ( ('MS_WIN_Services_Specific', 'MPG', {}), [], ['vmpg01x'], {'description': u'MPG Service'} ),
  ( ('MS_WIN_Services_Specific', 'StatusManagementService', {}), [], ['vnicview01x'], {'description': u'NicView'} ),
  ( ('MS_WIN_Services_Specific', 'DBSERVER', {}), [], ['vlighthouse01x'], {'description': u'Lighthouse LMS Professional Database Server'} ),
  ( ('MS_WIN_Services_Specific', 'LICENCESERVER', {}), [], ['vlighthouse01x'], {'description': u'Lighthouse LMS Professional License Server'} ),
  ( ('MS_WIN_Services_Specific', 'Data_Collector', {}), [], ['vlighthouse01x'], {'description': u'Lighthouse LWS Data Collector Service'} ),
  ( ('MS_WIN_Services_Specific', 'prime', {}), [], ['vgetprimet01x'], {'description': u'GETprimeVisit'} ),
  ( ('MS_WIN_Services_Specific', 'PCIGateway', {}), [], ['vnetnotify01x'], {'description': u'NetSupportNotify'} ),
  ( ('MS_WIN_Services_Specific', 'sshd', {}), [], ['vsysadm01x', 'vsysadm02x', 'vhighlander02x'], {'description': u'Windows SSH Daemon'} ),
  ( ('MS_WIN_Services_Specific', 'MiSeq', {}), [], ['vmiseq01x'], {'description': u'Miseq'} ),
  ( ('MS_WIN_Services_Specific', 'BI_PROD', {}), [], ['vsqltcognos01x'], {'description': u'Cognos WhereScape'} ),
] + static_checks['MS_WIN_Services_Specific']


rule_MS_WIN_Disk_Space = [
  ( {'group_defaults': {}, 'grouping_rules': [({'type': ['Volume']}, 'default'), ({'id': ('exact', u'Z:')}, 'exclude')], 'item_rules': [], 'group_rules': [], 'item_defaults': {}, 'grouping_opts': {}}, [], ['bexchmail01a', 'bexchmail01b'] ),
  ( {'group_defaults': {}, 'grouping_rules': [], 'item_rules': [({}, {'name': ('substr', u'C:\\MountPoints\\Data')}, {'used': {'warn': ('rel', 92.0), 'crit': ('rel', 95.0)}})], 'group_rules': [], 'item_defaults': {}, 'grouping_opts': {}}, [], ['bexchmail01a', 'bexchmail01b'], {'description': u'Exchange Mointpoints - Data 92%'} ),
  ( {'group_defaults': {}, 'grouping_rules': [], 'item_rules': [({}, {'name': ('substr', u'C:\\MountPoints\\Log')}, {'used': {'warn': ('rel', 60.0), 'crit': ('rel', 80.0)}})], 'group_rules': [], 'item_defaults': {}, 'grouping_opts': {}}, [], ['bexchmail01a', 'bexchmail01b'], {'description': u'Exchange Mointpoints - Log 60%'} ),
  ( {'group_defaults': {}, 'grouping_rules': [({'id': ('exact', u'Z:')}, 'exclude')], 'item_rules': [], 'group_rules': [], 'item_defaults': {}, 'grouping_opts': {}}, [], ALL_HOSTS ),
] + rule_MS_WIN_Disk_Space


active_checks.setdefault('check_certificate', [])

active_checks['check_certificate'] = [
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'insitedev.uzbrussel.be'}, [], ['vlrdev01x'], {'description': u'insitedev.uzbrussel.be - Cert check'} ),
  ( {'url': u'/launchCRS.html', 'warning': 90, 'critical': 30, 'urlhost': u'v3mgrouper04x.uzbrussel.be'}, [], ['v3mgrouper04x'], {'description': u'v3mgrouper04x.uzbrussel.be - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'asemon.uzbrussel.be'}, [], ['vasemon01x'], {'description': u'asemon.uzbrussel.be - Cert check'} ),
  ( {'url': u'/forcea', 'warning': 90, 'critical': 30, 'urlhost': u'dwhtest.uzbrussel.be'}, [], ['vdwhfront02x'], {'description': u'dwhtest.uzbrussel.be/forcea - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'epowerhrtest.uzbrussel.be'}, [], ['vepwrhrt01x'], {'description': u'https://epowerhrtest.uzbrussel.be - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'empoweruz.uzbrussel.be'}, [], ['vepwrhrp01x'], {'description': u'https://empoweruz.uzbrussel.be - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'humanuz-test.uzbrussel.be'}, [], ['vtestalf03x'], {'description': u'https://humanuz-test.uzbrussel.be/ - Cert check'} ),
  ( {'url': u'/iprova', 'warning': 90, 'critical': 30, 'urlhost': u'iprovatest.uzbrussel.be'}, [], ['viprovatest02x'], {'description': u'https://iprovatest.uzbrussel.be/iprova - Cert check'} ),
  ( {'url': u'/iprova', 'warning': 90, 'critical': 30, 'urlhost': u'iprovatest.uzbrussel.be'}, [], ['viprovaappl01x'], {'description': u'https://iprova.uzbrussel.be - Cert check'} ),
  ( {'url': u'/common/dashboard', 'warning': 90, 'critical': 30, 'urlhost': u'j2eetest.uzbrussel.be', 'port': u'7081'}, [], ['vweblogicdev01x'], {'description': u'https://j2eetest.uzbrussel.be:7081/common/dashboard - Cert check'} ),
  ( {'url': u'/mybox', 'warning': 90, 'critical': 30, 'urlhost': u'medimailacc.uzbrussel.be', 'port': u'8080'}, [], ['vmedimailacc01x'], {'description': u'https://medimailacc.uzbrussel.be:8080/mybox - Cert check'} ),
  ( {'url': u'/mybox', 'warning': 90, 'critical': 30, 'urlhost': u'medimail.uzbrussel.be', 'port': u'8080'}, [], ['vmedimail02x'], {'description': u'https://medimail.uzbrussel.be:8080/mybox - Cert check'} ),
  ( {'url': u'/webadmin/Index.action', 'warning': 90, 'critical': 30, 'urlhost': u'vmirthdev01x.uzbrussel.be', 'port': u'8443'}, [], ['vmirthdev01x'], {'description': u'https://vmirthdev01x.uzbrussel.be:8443/webadmin/Index.action - Cert check'} ),
  ( {'url': u'/webadmin/Index.action', 'warning': 90, 'critical': 30, 'urlhost': u'vmirthdev01x.uzbrussel.be', 'port': u'8444'}, [], ['vmirthdev01x'], {'description': u'https://vmirthdev01x.uzbrussel.be:8444/webadmin/Index.action - Cert check'} ),
  ( {'url': u'/oaziswebsvc/service.asmx', 'warning': 90, 'critical': 30, 'urlhost': u'voazistweb01x.uzbrussel.be'}, [], ['voazistweb01x'], {'description': u'https://voazistweb01x.uzbrussel.be/oaziswebsvc/service.asmx - Cert check'} ),
  ( {'url': u'/RDWeb', 'warning': 90, 'critical': 30, 'urlhost': u'vrdsbroker08x.uzbrussel.be'}, [], ['vrdsbroker08x'], {'description': u'https://vrdsbroker08x.uzbrussel.be/RDWeb - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'vredcapdev01x.uzbrussel.be'}, [], ['vredcapdev01x'], {'description': u'https://vredcapdev01x.uzbrussel.be/ - Cert check'} ),
  ( {'url': u'/index.html#!/login', 'warning': 90, 'critical': 30, 'urlhost': u'saltodev.uzbrussel.be', 'port': u'8100'}, [], ['vsaltodev01x'], {'description': u'https://saltodev.uzbrussel.be:8100/index.html#!/login'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'topdesktest.uzbrussel.be'}, [], ['vtopdeskit02x'], {'description': u'https://topdesktest.uzbrussel.be/'} ),
  ( {'url': u'/UltimoDevelopment/Ultimo.aspx', 'warning': 90, 'critical': 30, 'urlhost': u'ultimodev.uzbrussel.be'}, [], ['vultimodev01x'], {'description': u'https://ultimodev.uzbrussel.be/UltimoDevelopment/Ultimo.aspx - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'insitedev.uzbrussel.be'}, [], ['vlrdev01x'], {'description': u'https://insitedev.uzbrussel.be - Cert check'} ),
  ( {'url': u'/', 'warning': 30, 'critical': 90, 'urlhost': u'saga.uzbrussel.be'}, [], ['vsagap01x'], {'description': u'https://saga.uzbrussel.be - Cert check'} ),
  ( {'url': u'/forcea', 'warning': 90, 'critical': 30, 'urlhost': u'dwh.uzbrussel.be'}, [], ['vdwhfront01x'], {'description': u'dwh.uzbrussel.be/forcea - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'brightcnv-nipt-prod.uzbrussel.be'}, [], ['vbrighttools01x'], {'description': u'https://brightcnv-nipt-prod.uzbrussel.be - Cert Check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'vbrighttools03x.uzbrussel.be'}, [], ['vbrighttools03x'], {'description': u'https://vbrighttools03x.uzbrussel.be/ - Cert Check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'www.uzbrussel.be'}, [], ['vuzbpubweb01x'], {'description': u'www.uzbrussel.be - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'igp.uzbrussel.be'}, [], ['vigp01x'], {'description': u'https://igp.uzbrussel.be/igp-preview/#!simple_search - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 3, 'urlhost': u'healthdata.uzbrussel.be', 'port': u'8443'}, [], ['vhd4dp01x'], {'description': u'https://healthdata.uzbrussel.be:8443/#/login - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'humanuz.uzbrussel.be', 'port': u'8448'}, [], ['vehr01x'], {'description': u'https://humanuz.uzbrussel.be:8448/ - Cert check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'mediawiki.uzbrussel.be'}, [], ['vbrighttools02x'], {'description': u'https://mediawiki.uzbrussel.be/ - Cert Check'} ),
  ( {'url': u'/', 'warning': 90, 'critical': 30, 'urlhost': u'kitry.uzbrussel.be'}, [], ['vkitry01x'], {'description': u'https://kitry.uzbrussel.be/forms/frmservlet?config=UZ_PROD - Cert Check'} ),
  ( {'url': u'/RDWeb', 'warning': 90, 'critical': 30, 'urlhost': u'vrdsweb1601x.uzbrussel.be'}, [], ['vrdsweb1601x'], {'description': u'https://vrdsweb1601x.uzbrussel.be/RDWeb - Cert check'} ),
  ( {'url': u'/RDWeb', 'warning': 90, 'critical': 30, 'urlhost': u'vrdsweb1602x.uzbrussel.be'}, [], ['vrdsweb1602x'], {'description': u'https://vrdsweb1602x.uzbrussel.be/RDWeb - Cert check'} ),
] + active_checks['check_certificate']


rule_Solaris_IO_statistics = [
  ( {'grouping_opts': {}, 'item_defaults': {'thresholds': {'iostat3.%b': {'warn': (u'\u2265', 'absolute', 95, ''), 'crit': (u'\u2265', 'absolute', 99, '')}, 'iostat3.asvc_t': {'warn': (u'\u2265', 'absolute', 100.0, ''), 'crit': (u'\u2265', 'absolute', 150.0, '')}}}, 'item_rules': []}, [], ALL_HOSTS ),
] + rule_Solaris_IO_statistics


rule_NetApp_Spaces = [
  ( {'group_defaults': {}, 'grouping_rules': [], 'item_rules': [({}, {'Name': ('exact', u'vs03_echoPhilips')}, {'used_volume': {'warn': ('rel_volume', 97.0), 'crit': ('rel_volume', 98.0)}}), ({}, {'Name': ('exact', u'vs03_sdrives')}, {'used_volume': {'warn': ('rel_volume', 97.0), 'crit': ('rel_volume', 98.0)}})], 'group_rules': [], 'item_defaults': {}, 'grouping_opts': {}}, [], ['uzb-mca'], {'comment': u'UZB-MCA : \nWarning threshold : 97%\nCritical threshold : 98%\n', 'description': u'Netapp UZB-MCA : volumes 97 - 98'} ),
  ( {'group_defaults': {}, 'grouping_rules': [], 'item_rules': [({}, {'Name': ('exact', u'agfa_sas')}, {'used_volume': {'warn': ('abs_volume', 536870912000), 'crit': ('abs_volume', 268435456000)}})], 'group_rules': [], 'item_defaults': {}, 'grouping_opts': {}}, [], ['uzb-mcb'], {'comment': u'UZB-MCB : \nWarning threshold : less than 500 GB\nCritical threshold : less than 250 GB\n', 'description': u'Netapp UZB-MCB : Agfa SAS'} ),
  ( {'group_defaults': {}, 'grouping_rules': [], 'item_rules': [({}, {'Name': ('exact', u'vs05_web_cache')}, {'used_volume': {'warn': ('rel_volume', 99.0), 'crit': ('rel_volume', 99.5)}}), ({}, {'Name': ('exact', u'vs05_web_cache2')}, {'used_volume': {'warn': ('abs_volume', 536870912000), 'crit': ('abs_volume', 268435456000)}})], 'group_rules': [], 'item_defaults': {}, 'grouping_opts': {}}, [], ['uzb-tier1a'] ),
] + rule_NetApp_Spaces


extra_service_conf.setdefault('retry_interval', [])

extra_service_conf['retry_interval'] = [
  ( 2.0, [], ['I_hosp62', 'I_hosp63', 'I_hosp43'], ALL_SERVICES ),
  ( 2.0, ['os_srv_win_2k8r2', ], ALL_HOSTS, ALL_SERVICES ),
  ( 2.0, ['os_srv_win_2k8rtm', ], ALL_HOSTS, ALL_SERVICES ),
] + extra_service_conf['retry_interval']

