[package]
name    = "sql_protocol"
version = "0.1.0"
authors = ["Vincent Stuyck <vst@si-int.eu>"]
repository = "https://github.com/ContinuousC/SmartAgent"
license = "Elastic-2.0"
edition = "2021"
publish = false

[dependencies]
odbc-api = "0.57.0"
serde = { version = "1.0.163", features = ["derive"] }


wmi_protocol = { path = "../wmi" }
agent_utils = { path = "../../agent_utils", features = ["key-reader"]}
etc = { path = "../../etc" }
etc_base = { path = "../../etc_base" }
protocol = { path = "../../protocol" }
value = { path = "../../value" }
thiserror = "1.0.40"
log = "0.4.17"
# mssql-browser = { version = "0.1.1", features = ["tokio"] }
#mssql-browser = { path = "../../external/mssql-browser", features = ["tokio"] }
trust-dns-resolver = "0.22.0"
tokio = { version = "1.0", features = [ "full", "tracing" ] }
chrono = { version = "0.4", features = [ "serde" ] }
async-trait = "0.1.68"
lazy_static = "1.4.0"
force-send-sync = "1.0.0"
futures = "0.3.28"
logger = { path = "../../logger" }
serde_json = "1.0.96"
ron = "0.8.0"
itertools = "0.10.5"
tap = "1.0.1"
erased-serde = "0.4.5"
