[package]
name    = "azure_protocol"
version = "0.1.0"
authors = ["Maarten Deprez <mdp@si-int.eu>", "Vincent Stuyck <vst@si-int.eu>"]
repository = "https://github.com/ContinuousC/SmartAgent"
license = "Elastic-2.0"
edition = "2021"
publish = false


[dependencies]
thiserror           = "1.0"
reqwest      		= { version = "0.12.7", features = ["json", "cookies", "native-tls"] }
chrono       		= { version = "0.4.11", features = ["serde"] }
serde        		= { version = "1.0", features = ["derive"] }
tokio               = { version = "1.0", features = [ "fs", "io-util" ] }
serde_json   		= "1.0"
log                 = "0.4.14"
lazy_static  		= "1.4.0"
regex               = "1.5.5"
async-trait         = "0.1"
futures             = "0.3.21"

agent_utils = { path = "../../agent_utils", features = ["key-reader"]}
agent_serde = { path = "../../agent_serde" }
etc = { path = "../../etc" }
etc_base = { path = "../../etc_base" }
protocol = { path = "../../protocol" }
value = { path = "../../value" }
uritemplate = { path = "../../uritemplate/"}
rest_protocol = { path = "../rest"}
logger = { path = "../../logger" }